const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve('.test-profile/chronicles-'+Date.now()));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{const w=new BrowserWindow({show:false,width:1600,height:1000,webPreferences:{offscreen:true,backgroundThrottling:false}}),checks=[],errors=[],out='test-output/chronicles';fs.mkdirSync(out,{recursive:true});const run=c=>w.webContents.executeJavaScript('(()=>eval('+JSON.stringify(c)+'))()',true),wait=ms=>new Promise(r=>setTimeout(r,ms)),check=async(n,c)=>{assert.ok(await run(c),n);checks.push(n);console.log('PASS '+n)};w.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message)});try{await w.loadFile(path.resolve(process.argv.includes('--packaged')?'dist/win-unpacked/resources/app.asar/index.html':'index.html'));for(let i=0;i<250&&!await run('assetReady');i++)await wait(100);await check('startup and compatible old saves',"assetReady&&K.migrate({version:3,gold:453,maps:['ice'],characters:['nivor'],weapons:['absolute']}).gold===453&&Object.keys(K.migrate({}).bestiary).length===0");
await run("save=K.defaults();save.maps=Object.keys(C.maps);save.characters=Object.keys(C.characters);save.weapons=Object.keys(C.weapons);save.options.testArsenal=false;save.selectedMap='profane';save.selectedCharacter='malthor';begin();state='paused'");
await check('Profane-only stats preserve other chapters',"(()=>{const slot={id:'absolute',level:7},base=K.stats(slot,{map:'ice'}),pro=K.stats(slot,{map:'profane'});return base.damage===K.stats(slot,{}).damage&&pro.damage<base.damage&&pro.interval>=pro.duration&&pro.radius<base.radius})()");
await check('storm overlap is bounded per weapon',"(()=>{effects=[];for(let j=0;j<8;j++){effect({kind:'storm',weapon:'absolute',life:2});effect({kind:'storm',weapon:'verdict',life:2});}const ok=effects.length===2;effects=[];return ok})()");
await check('effective damage and final killing blow count once',"(()=>{const e=newEnemy('fanatic',{...player});e.hp=10;enemies=[e];run.report=RubraChronicleCore.report();damageEnemy(e,900,{weapon:'absolute'});damageEnemy(e,900,{weapon:'absolute'});return run.report.weapons.absolute.damage===10&&run.report.weapons.absolute.kills===1&&save.bestiary.fanatic===1})()");
await check('Rosary leaves an inner opening only in Profane',"(()=>{save.selectedCharacter='vespera';begin();const e=newEnemy('flesh',{x:player.x+12,y:player.y});enemies=[e];fire({id:'rosary',level:1});const safe=e.hp===e.maxHp;e.x=player.x+65;fire({id:'rosary',level:1});state='paused';return safe&&e.hp<e.maxHp})()");
await check('gargoyle resists slow and attacks at close range',"(()=>{const e=newEnemy('profaneGargoyle',{...player});enemies=[e];damageEnemy(e,1,{weapon:'absolute',slow:.35,slowTime:3});e.meleeClock=0;RubraChronicles.melee(e,.1);return e.slowFactor>=.85&&e.telegraph.kind==='slam'&&e.telegraph.time>=1&&e.cfg.behavior==='chase'})()");
await check('melee lunge gives warning and continuous slow gets recovery',"(()=>{const p=K.nearestPoint({x:player.x+120,y:player.y},map,13),e=newEnemy('fanatic',p);e.meleeClock=0;RubraChronicles.melee(e,.1);const warned=e.telegraph?.kind==='lunge'&&e.telegraph.time>=.8;e.slowTimer=4;e.slowFactor=.65;e.slowExposure=1.5;RubraChronicles.melee(e,.1);return warned&&e.resolve>0&&e.slowFactor===1})()");
await check('crystal event protects nearby mobs and rewards once',"(()=>{enemies=[];run.encounterEvent=null;run.eventIndex=0;RubraChronicles.start('crystals');const ev=run.encounterEvent,crystals=enemies.filter(e=>e.cfg.object),dummy=newEnemy('fanatic',{x:ev.x,y:ev.y}),before=run.gold,protectedAmount=RubraChronicles.incoming(dummy,100);for(const c of crystals)damageEnemy(c,1e9,{weapon:'bloodwhip'});RubraChronicles.update(.1);RubraChronicles.finish(true);return crystals.length>0&&protectedAmount===85&&run.gold===before+70&&run.report.events.length===1&&!save.bestiary.eventCrystal})()");
await check('event pauses and survives checkpoint migration',"(()=>{enemies=[];run.encounterEvent=null;run.eventIndex=1;RubraChronicles.start('marked');state='paused';const deadline=run.encounterEvent.deadline;update(5);snapshot();const restored=K.migrate(save);return run.encounterEvent.deadline===deadline&&restored.active.encounterEvent.type==='marked'&&restored.active.entities.some(e=>e.eventRole==='marked:1')})()");
await check('resume preserves marked health and never duplicates objectives',"(()=>{const hp=enemies[0].hp;snapshot();begin(true);state='paused';return enemies.filter(e=>e.eventRole==='marked:1').length===1&&Math.abs(enemies.find(e=>e.eventRole==='marked:1').hp-hp)<.01&&run.encounterEvent.type==='marked'})()");
await check('failed event never credits reward',"(()=>{const gold=run.gold;run.encounterEvent.deadline=elapsed-1;RubraChronicles.update(.1);return run.gold===gold&&run.report.events.at(-1).won===false})()");
await check('altar requires guarding and loses integrity when contested',"(()=>{enemies=[];run.encounterEvent=null;RubraChronicles.start('altar');const ev=run.encounterEvent;player.x=ev.x;player.y=ev.y;RubraChronicles.update(1);const progress=ev.progress;enemies=[newEnemy('fanatic',{x:ev.x+30,y:ev.y})];RubraChronicles.update(1);return progress===1&&ev.progress===1&&ev.hp<100})()");
await check('altar success and boss cancellation settle only once',"(()=>{enemies=[];run.encounterEvent.progress=C.events.altarGoal;RubraChronicles.update(.1);const complete=run.report.events.at(-1).won;run.eventIndex=0;RubraChronicles.start('crystals');run.bossSpawned=true;RubraChronicles.update(.1);return complete&&!run.encounterEvent&&!enemies.some(e=>e.cfg.object)&&run.report.events.at(-1).won===false})()");
await check('tutorial never schedules events',"(()=>{save.selectedMap='tutorial';save.selectedCharacter='rubra';begin();elapsed=120;RubraChronicles.update(1);state='paused';return !run.encounterEvent})()");
await check('actual received damage excludes invulnerability',"(()=>{state='playing';player.invuln=0;player.dash=0;player.hp=5;damagePlayer(2);damagePlayer(2);state='paused';return run.report.damageTaken===2})()");
await run("finish(false);$('openReport').click()");await check('report survives settlement and displays equipped weapons',"state==='report'&&save.lastResult.report.damageTaken===2&&document.querySelectorAll('#report tbody tr').length>0&&$('reportContent').textContent.includes('Lâmina ancestral')");
await run("$('reportBack').click();menu();$('optionsButton').click();$('openBestiary').click()");await check('bestiary uses real victories and locked portraits',"state==='bestiary'&&$('bestiaryCards').textContent.includes('Monge Fanático')&&$('bestiaryCards').textContent.includes('Registro não descoberto')");
await run("$('showRelics').click()");await check('relic collection honors existing unlocks',"$('bestiaryCards').children.length===3&&$('bestiaryCards').textContent.includes('NA COLEÇÃO')");
await run("$('bestiaryBack').click();$('openMusicLibrary').click();document.querySelector('[data-track=oath]').click();RubraAudio.tick(state,'tutorial',false)");await check('manual music overrides current menu with exclusive track',"RubraAudio.engine.manual==='oath'&&RubraAudio.engine.currentTrack.id==='oath'&&document.querySelectorAll('[data-track]').length===11");
await check('end of manual track returns to automatic selection',"(()=>{const e=RubraAudio.engine;e.step=e.currentTrack.steps;e.next=e.ctx.currentTime;e.menuTick();RubraAudio.tick('maps','ice',false);return !e.manual&&e.scene==='maps'&&e.currentTrack.scene==='maps'})()");
await check('combat never inherits a manual menu track',"(()=>{RubraAudio.engine.selectTrack('oath');RubraAudio.tick('playing','profane',true);return !RubraAudio.engine.manual&&RubraAudio.engine.scene==='boss'})()");
await check('laboratory collection never credits campaign',"(()=>{storeSave();const count=save.bestiary.fanatic||0;switchProfile('laboratory');save.bestiary.fanatic=999;storeSave();switchProfile('campaign');return save.bestiary.fanatic===count})()");
for(const [width,height]of [[1600,1000],[1360,768],[420,850]]){w.setSize(width,height);for(const page of ['bestiary','musicLibrary','report']){if(page==='bestiary'){await run("save.bestiary.fanatic=10;RubraCollections.book();$('showCreatures').click()");}else if(page==='musicLibrary')await run('RubraCollections.music()');else await run('RubraCollections.report()');await wait(400);await check(page+' accessible at '+width,"(()=>{const d=document.querySelector('#'+state+' .dialog');return d&&d.clientWidth>100&&d.scrollWidth<=d.clientWidth+2&&getComputedStyle(d).overflowY==='auto'})()");fs.writeFileSync(out+'/'+page+'-'+width+'.png',(await w.webContents.capturePage()).toPNG());}}
w.setSize(1360,768);await run("save.selectedMap='profane';save.selectedCharacter='vespera';begin();spawnClock=999;player.invuln=100;run.eventIndex=0");for(const type of ['altar','crystals','marked']){await run("enemies=[];run.encounterEvent=null;RubraChronicles.start('"+type+"');render()");await wait(400);await check(type+' objective renders in live combat',"!$('eventHud').classList.contains('hidden')&&run.encounterEvent.type==='"+type+"'");fs.writeFileSync(out+'/event-'+type+'.png',(await w.webContents.capturePage()).toPNG());}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' chronicles checks passed');app.exit();}catch(e){console.error(e);fs.writeFileSync(out+'/failure.txt',e.stack);app.exit(1)}});
