const test=require('node:test'),assert=require('node:assert/strict');const C=require('../src/config.js'),K=require('../src/core.js');
test('old record migration and valid selections',()=>{const s=K.migrate({gold:-20,selectedCharacter:'missing',weapons:['evil','ember'],best:10},123);assert.equal(s.best,123);assert.equal(s.gold,0);assert.equal(s.selectedCharacter,'rubra');assert.deepEqual(s.weapons,['blade','ember']);});
test('save reload settlement is idempotent for every end reason',()=>{for(const outcome of ['victory','death','abandon']){const s=K.defaults(),r={id:'run1',gold:17,kills:5,elapsed:40,map:'tutorial'};s.active=r;assert.ok(K.settle(s,r,outcome));assert.equal(s.gold,17);const reload=K.migrate(JSON.parse(JSON.stringify(s)));assert.equal(K.settle(reload,r,outcome),false);assert.equal(reload.gold,17);}});
test('resume does not credit pending gold',()=>{const s=K.migrate({version:2,gold:12,active:{id:'a',character:'noctis',map:'tutorial',gold:30,weapons:[{id:'dagger',level:2}],player:{x:408,y:302,hp:3}}});assert.equal(s.gold,12);assert.equal(s.active.gold,30);});
test('slots, maximum levels and locked offers',()=>{const s=K.defaults();s.weapons.push('dagger');const r={weapons:[{id:'blade',level:5}],gold:0};assert.deepEqual(K.choices(r,s).map(c=>c.id),['dagger']);assert.equal(K.upgrade(r,s,{kind:'weapon',id:'lance'}),false);s.weapons=Object.keys(C.weapons);r.weapons=s.weapons.map(id=>({id,level:5}));assert.deepEqual(K.choices(r,s).map(c=>c.kind),['heal','gold']);assert.equal(K.upgrade(r,s,{kind:'weapon',id:'blade'}),false);const previous=C.slots;C.slots=1;assert.ok(K.choices({weapons:[{id:'blade',level:1}]},s).every(c=>c.id==='blade'));C.slots=previous;});
test('weapon upgrades preserve occupied slots and all modifiers apply',()=>{const s=K.defaults();s.weapons.push('dagger');const r={weapons:[{id:'dagger',level:1}]};assert.ok(K.upgrade(r,s,{kind:'weapon',id:'dagger'}));assert.equal(r.weapons.length,1);const a=K.stats(r.weapons[0]),b=K.stats(r.weapons[0],{damage:2,attackSpeed:2,range:2});assert.equal(b.damage,a.damage*2);assert.equal(b.interval,a.interval/2);assert.equal(b.range,a.range*2);});
test('death callback and rewards only once',()=>{let count=0;const e={hp:5};K.hit(e,5,()=>count++);K.hit(e,5,()=>count++);assert.equal(count,1);assert.equal(e.hp,0);});
test('spawns avoid obstacles, edges and player for all actors',()=>{for(const m of Object.values(C.maps))for(let i=0;i<500;i++){const p=K.freePoint(m,m.spawn,175,31);assert.ok(p);assert.ok(K.validPoint(p,m,31));assert.ok(Math.hypot(p.x-m.spawn.x,p.y-m.spawn.y)>=175);}});
test('unlocks are attainable without their weapon and idempotent',()=>{const s=K.defaults(),r={map:'necropolis',elapsed:61,bossKilled:false};assert.deepEqual(K.unlock(s,r),['dagger','ember','thorns']);assert.deepEqual(K.unlock(s,r),[]);r.bossKilled=true;assert.deepEqual(K.unlock(s,r),['lance']);});
test('corrupted save backup and fallback',()=>{const m=new Map([['rubra-save-v2','bad json'],['rubra-best','77']]),storage={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};const s=K.load(storage);assert.equal(s.best,77);assert.equal(m.get('rubra-save-v2-unreadable-backup'),'bad json');});
test('saved weapon duplicates and invalid positions repaired',()=>{const s=K.migrate({active:{id:'x',map:'tutorial',character:'rubra',weapons:[{id:'blade',level:999},{id:'blade',level:1}],player:{x:-999,y:0}}});assert.equal(s.active.weapons.length,1);assert.equal(s.active.weapons[0].level,5);assert.ok(K.validPoint(s.active.player,C.maps.tutorial));});

test('fresh campaign starts with Rubra and tutorial only',()=>{const s=K.defaults();assert.equal(s.selectedCharacter,'rubra');assert.deepEqual(s.characters,['rubra']);assert.deepEqual(s.maps,['tutorial']);assert.deepEqual(s.weapons,['blade']);assert.equal(s.version,3);});
test('tutorial survival grants its second weapon but only boss completion unlocks chapter',()=>{const s=K.defaults(),r={map:'tutorial',elapsed:160,bossKilled:false};assert.deepEqual(K.unlock(s,r),['acorn']);assert.deepEqual(s.maps,['tutorial']);assert.deepEqual(s.characters,['rubra']);r.bossKilled=true;assert.deepEqual(K.unlock(s,r),['dagger']);assert.ok(s.maps.includes('necropolis'));assert.ok(s.characters.includes('noctis'));assert.deepEqual(s.completedMaps,['tutorial']);assert.deepEqual(K.unlock(s,r),[]);assert.equal(s.maps.length,2);});
test('map arsenal filters acquisitions, including direct requests',()=>{const s=K.defaults();s.weapons=Object.keys(C.weapons);const r={map:'tutorial',weapons:[{id:'blade',level:1}]};for(let i=0;i<30;i++)assert.ok(K.choices(r,s).every(c=>['blade','acorn'].includes(c.id)));assert.equal(K.upgrade(r,s,{kind:'weapon',id:'lance'}),false);assert.equal(K.upgrade(r,s,{kind:'weapon',id:'acorn'}),true);r.map='necropolis';assert.equal(K.upgrade(r,s,{kind:'weapon',id:'lance'}),true);assert.equal(K.startWeapon('noctis','tutorial'),'blade');assert.equal(K.startWeapon('noctis','necropolis'),'dagger');});
test('v2 saves retain content, gold, selected hero and ongoing arsenal',()=>{const old={version:2,gold:157,maps:['tutorial','necropolis'],weapons:['blade','dagger','lance'],selectedCharacter:'noctis',selectedMap:'necropolis',active:{id:'old',map:'tutorial',character:'noctis',weapons:[{id:'lance',level:3}],player:{x:408,y:302,hp:4},gold:8}};const s=K.migrate(old);assert.equal(s.version,3);assert.equal(s.gold,157);assert.equal(s.selectedCharacter,'noctis');assert.equal(s.selectedMap,'necropolis');assert.equal(s.active.weapons[0].id,'lance');assert.equal(s.active.gold,8);assert.ok(K.upgrade(s.active,s,{kind:'weapon',id:'lance'}));assert.deepEqual(K.migrate(s),s);});
test('v3 locked selections and runs are repaired',()=>{const s=K.migrate({version:3,selectedCharacter:'noctis',selectedMap:'necropolis',active:{id:'x',map:'necropolis',character:'noctis'}});assert.equal(s.selectedCharacter,'rubra');assert.equal(s.selectedMap,'tutorial');assert.equal(s.active,null);});
test('laboratory unlocks require test profile and validate all identifiers',()=>{const s=K.defaults();assert.equal(K.laboratoryUnlock(s,'campaign','maps',['necropolis']),false);assert.deepEqual(s.maps,['tutorial']);assert.equal(K.laboratoryUnlock(s,'laboratory','roles',['admin']),false);assert.equal(K.laboratoryUnlock(s,'laboratory','weapons',['invalid']),false);assert.ok(K.laboratoryUnlock(s,'laboratory','characters',['noctis','noctis']));assert.equal(s.characters.length,2);});
test('laboratory and campaign saves do not share gold, record or unlocks',()=>{const m=new Map([['rubra-best','99']]),storage={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};const campaign=K.load(storage),lab=K.load(storage,C.profiles.laboratory);assert.equal(lab.best,0);K.laboratoryUnlock(lab,'laboratory','maps',['necropolis']);lab.gold=999;K.persist(storage,campaign);K.persist(storage,lab,C.profiles.laboratory);assert.equal(K.load(storage).gold,0);assert.deepEqual(K.load(storage).maps,['tutorial']);assert.equal(K.load(storage,C.profiles.laboratory).gold,999);});

const World=require('../src/world.js');
test('large necropolis camera follows player and clamps to finite edges',()=>{const m=C.maps.necropolis;assert.deepEqual(World.camera(m,{x:100,y:100}),{x:0,y:0});assert.deepEqual(World.camera(m,{x:1500,y:900}),{x:1020,y:630});assert.deepEqual(World.camera(m,{x:99999,y:99999}),{x:1920,y:1080});assert.deepEqual(World.camera(C.maps.tutorial,{x:700,y:400}),{x:0,y:0});});
test('new world keeps previous spawn and obstacles valid while expanding ninefold',()=>{const m=C.maps.necropolis;assert.equal(m.world.width*m.world.height,960*540*9);assert.equal(m.obstacles.length,54);assert.ok(K.validPoint(m.spawn,m));assert.ok(m.obstacles.some(o=>o.x===180&&o.y===155));assert.ok(m.obstacles.every(o=>o.x>m.bounds.x&&o.y>m.bounds.y&&o.x<m.bounds.x+m.bounds.w&&o.y<m.bounds.y+m.bounds.h));});
test('world enemy spawns remain near player and avoid obstacles at every edge',()=>{const m=C.maps.necropolis;for(const player of [m.spawn,{x:1450,y:950},{x:65,y:90},{x:2810,y:1560}])for(let i=0;i<100;i++){const p=K.spawnPoint(m,player,175,31);assert.ok(p);assert.ok(K.validPoint(p,m,31));const d=Math.hypot(p.x-player.x,p.y-player.y);assert.ok(d>=175-1e-6&&d<=m.world.spawnOuter+1e-6);}});

test('laboratory reset preserves wealth and preferences and settles checkpoint only once',()=>{const s=K.defaults();s.gold=71;s.best=42;s.options.testArsenal=false;for(const type of ['characters','maps','weapons'])K.laboratoryUnlock(s,'laboratory',type,Object.keys(C[type]));s.selectedCharacter='noctis';s.selectedMap='necropolis';s.completedMaps=['tutorial'];s.active={id:'reset-run',gold:19,kills:3,elapsed:20,map:'necropolis'};const before=JSON.stringify(s);assert.equal(K.laboratoryReset(s,'campaign'),false);assert.equal(JSON.stringify(s),before);assert.ok(K.laboratoryReset(s,'laboratory'));assert.equal(s.gold,90);assert.equal(s.best,42);assert.equal(s.options.testArsenal,false);assert.deepEqual(s.characters,['rubra']);assert.deepEqual(s.maps,['tutorial']);assert.deepEqual(s.weapons,['blade']);assert.deepEqual(s.completedMaps,[]);assert.equal(s.selectedCharacter,'rubra');assert.equal(s.selectedMap,'tutorial');assert.equal(s.active,null);assert.ok(K.laboratoryReset(s,'laboratory'));assert.equal(s.gold,90);assert.deepEqual(K.migrate(s),s);});
