const {app,BrowserWindow,nativeImage}=require('electron'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve('.test-profile/ice-polish'));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{const out=path.resolve('test-output/ice-polish');fs.mkdirSync(out,{recursive:true});const win=new BrowserWindow({show:false,width:1600,height:900,webPreferences:{offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),errors=[],checks=[];win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message)});const run=c=>win.webContents.executeJavaScript('(()=>eval('+JSON.stringify(c)+'))()',true),wait=ms=>new Promise(r=>setTimeout(r,ms)),check=async(n,c)=>{assert.ok(await run(c),n);checks.push(n);console.log('PASS '+n)},shot=async n=>{await wait(250);fs.writeFileSync(path.join(out,n+'.png'),(await win.webContents.capturePage()).toPNG())};
try{await win.loadFile(path.resolve(process.argv.includes('--packaged')?'dist/win-unpacked/resources/app.asar/index.html':'index.html'));for(let i=0;i<250&&!await run('assetReady');i++)await wait(100);await check('all visual assets initialize without failure','assetReady');await run("profile='laboratory';save=K.defaults();K.laboratoryUnlock(save,profile,'maps',Object.keys(C.maps));K.laboratoryUnlock(save,profile,'characters',Object.keys(C.characters));K.laboratoryUnlock(save,profile,'weapons',Object.keys(C.weapons));save.selectedMap='ice';save.selectedCharacter='vespera';begin();state='paused';");
await check('reported trees pillars portal and swords are solid',"[[400,180],[623,150],[1145,200],[1286,275],[1370,355],[336,660],[1345,630],[1182,640],[595,663],[1385,800]].every(([x,y])=>!K.validPoint({x:x*2.4,y:y*2360/984},map,8))");
await check('cross roads remain open',"[[800,200],[800,500],[800,870],[400,520],[1200,520],[450,700],[1000,700]].every(([x,y])=>K.validPoint({x:x*2.4,y:y*2360/984},map,8))");
await check('dash cannot cross a rune shaft',"(()=>{const p={x:2990,y:650,r:8};moveBody(p,300,0);return p.x<1258*2.4})()");
await check('saved position inside new collision is repaired',"(()=>{const p=K.nearestPoint({x:1286*2.4,y:275*2360/984},map,8);return K.validPoint(p,map,8)})()");
await check('fairies are separate transparent foreground layers',"RubraIcePolish.fairies.length===3&&RubraIcePolish.fairies.every(f=>{const a=f.image.getContext('2d').getImageData(0,0,f.w,f.h).data;let zero=0,solid=0;for(let i=3;i<a.length;i+=4){zero+=a[i]===0;solid+=a[i]>100;}return zero>f.w*f.h*.4&&solid>100})");
await check('eight fire frames have transparent surroundings',"RubraIcePolish.fireFrames.length===8&&RubraIcePolish.fireFrames.every(f=>f.getContext('2d').getImageData(0,0,1,1).data[3]===0)");
await check('prism silhouette has real alpha and no opaque square',"(()=>{const im=RubraProfane.weaponImages.prism,q=im.getContext('2d'),a=q.getImageData(0,0,im.width,im.height).data;let z=0;for(let i=3;i<a.length;i+=4)z+=a[i]===0;return z>a.length/4*.2})()");
await check('each ice creature and Skarn visibly animate',"Object.keys(RubraIcePolish.frames).every(id=>{const c=document.createElement('canvas');c.width=c.height=180;const q=c.getContext('2d'),e={x:90,cfg:{asset:id,size:118}};RubraIcePolish.enemy(q,e,90,150,.1,false);const a=c.toDataURL();q.clearRect(0,0,180,180);RubraIcePolish.enemy(q,e,90,150,.7,false);return a!==c.toDataURL()})");
await check('all walkable ice regions connect',"(()=>{const b=map.bounds,step=35,nx=Math.ceil(b.w/step),ny=Math.ceil(b.h/step),good=new Set();for(let y=0;y<ny;y++)for(let x=0;x<nx;x++)if(K.validPoint({x:b.x+x*step,y:b.y+y*step},map,9))good.add(y*nx+x);const seed=[...good].reduce((a,k)=>{const d=k=>Math.hypot(b.x+k%nx*step-map.spawn.x,b.y+Math.floor(k/nx)*step-map.spawn.y);return d(k)<d(a)?k:a}),seen=new Set([seed]),queue=[seed];for(let j=0;j<queue.length;j++){const k=queue[j];for(const n of [k-1,k+1,k-nx,k+nx])if(good.has(n)&&!seen.has(n)){const p={x:b.x+k%nx*step,y:b.y+Math.floor(k/nx)*step},z={x:b.x+n%nx*step,y:b.y+Math.floor(n/nx)*step};if(Math.hypot(p.x-z.x,p.y-z.y)<=step+1&&K.clearSegment(p,z,map,9)){seen.add(n);queue.push(n)}}}return seen.size/good.size>.985})()");
for(const [w,h]of [[1600,900],[1360,960],[420,850]]){win.setSize(w,h);await wait(100);await check('arena fills viewport '+w,"(()=>{const r=$('arena').getBoundingClientRect();return r.left===0&&r.top===0&&r.width===innerWidth&&r.height===innerHeight&&document.documentElement.scrollWidth===innerWidth})()");await shot('hud-'+w);}
win.setSize(1600,900);await run("player.x=219*2.4;player.y=230*2360/984;render()");await shot('fairy');await run("player.x=1160*2.4;player.y=690*2360/984;effects=[];effect({kind:'beam',weapon:'prism',x:player.x,y:player.y-8,tx:player.x+350,ty:player.y+90,r:11,color:'#aaffef',life:.3,max:.5});render()");await shot('prism');
await run("save.selectedMap='profane';begin();state='paused';player.x=768*2.5;player.y=692*2.5;render()");await shot('flames');
const sheet=await run("(()=>{const c=document.createElement('canvas');c.width=1000;c.height=430;const q=c.getContext('2d');q.fillStyle='#160b24';q.fillRect(0,0,1000,430);Object.keys(RubraIcePolish.frames).forEach((id,i)=>{const e={x:60+i*135,cfg:{asset:id,size:110}};RubraIcePolish.enemy(q,e,e.x,135,.1,false);RubraIcePolish.enemy(q,e,e.x,280,.7,false)});RubraIcePolish.fireFrames.forEach((im,i)=>q.drawImage(im,i*90+10,330,45,80));const im=RubraProfane.weaponImages.prism;q.drawImage(im,830,300,55,125);return c.toDataURL()})()");fs.writeFileSync(path.join(out,'animation-sheet.png'),Buffer.from(sheet.split(',')[1],'base64'));
const icon=nativeImage.createFromPath('assets/branding/rubra-icon.png');assert.ok(!icon.isEmpty());assert.ok(fs.readFileSync('assets/branding/rubra.ico').readUInt16LE(4)===6);checks.push('application icon has six Windows sizes');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(checks.length+' checks passed');app.exit();
}catch(e){console.error(e);fs.writeFileSync(path.join(out,'failure.txt'),e.stack+'\n'+errors.join('\n'));app.exit(1)}});
