const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve('.test-profile/music-update'));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const out=path.resolve('test-output/music-update');fs.mkdirSync(out,{recursive:true});const win=new BrowserWindow({show:false,width:1500,height:900,webPreferences:{offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),errors=[],checks=[];
 win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message)});
 const run=c=>win.webContents.executeJavaScript('(()=>eval('+JSON.stringify(c)+'))()',true),wait=ms=>new Promise(r=>setTimeout(r,ms)),check=async(n,c)=>{assert.ok(await run(c),n);checks.push(n);console.log('PASS '+n)};
 try{
  await win.loadFile(path.resolve(process.argv.includes('--packaged')?'dist/win-unpacked/resources/app.asar/index.html':'index.html'));for(let i=0;i<250&&!await run('assetReady');i++)await wait(100);await check('all assets load','assetReady');
  await check('nine compositions in three exclusive playlists, plus both original tracks',"(()=>{const m=RubraMenuMusic,p=m.playlists;return m.pieces.length===9&&p.menu.length===5&&p.characters.length===3&&p.maps.length===3&&Object.entries(p).every(([scene,list])=>list.every(t=>t.scene===scene))&&new Set(Object.values(p).flat().map(t=>t.id)).size===11&&p.menu.filter(t=>t.legacy).length===2})()");
  await check('all full scores have finite notes, dynamics, distinct arrangements and advertised duration',"(()=>{const hashes=[];for(const p of RubraMenuMusic.pieces){let sig='',count=0;for(let i=0;i<p.steps;i++){const es=RubraMenuMusic.events(p,i);for(const e of es){if(!Number.isFinite(e.note)||e.note<12||e.note>108||e.duration<=0||e.volume<0||!Number.isFinite(e.delay))return false;count++;}sig+=es.map(e=>e.note+':'+e.volume.toFixed(3)).join(',');}if(count<900||Math.abs(p.steps*30/p.bpm-p.duration)>.001)return false;hashes.push(sig);}return new Set(hashes).size===9})()");
  await check('playlist boundaries wrap and each menu resumes its own position',"(()=>{const a=new RubraAudio.Engine(new OfflineAudioContext(1,22050,22050));a.tone=()=>{};a.setOptions({music:true,sound:false,musicVolume:.4,effectsVolume:0});a.setScene('characters');a.step=a.currentTrack.steps;a.tick();if(a.trackIndex!==1||a.step!==1)return false;a.step=73;a.setScene('maps');a.step=21;a.setScene('characters');if(a.trackIndex!==1||a.step!==73)return false;a.setScene('maps');if(a.step!==21)return false;a.trackIndex=2;a.step=a.currentTrack.steps;a.next=0;a.tick();const ok=a.trackIndex===0;a.dispose();return ok})()");
  await check('muting freezes sequence without catch-up or changing tracks',"(()=>{const a=new RubraAudio.Engine(new OfflineAudioContext(1,22050,22050));a.setScene('maps');a.step=31;a.setOptions({music:false,sound:false,musicVolume:.4,effectsVolume:0});a.tick();const ok=a.step===31&&a.voices.size===0;a.dispose();return ok})()");
  await check('navigation selects the correct scene and pauses outside requested menus',"(()=>{RubraAudio.unlock();RubraPreferences.music=true;for(const [state,scene]of [['menu','menu'],['characters','characters'],['maps','maps'],['options',''],['paused',''],['playing','ice']]){RubraAudio.tick(state,'ice',false);if(RubraAudio.engine.scene!==scene)return false;}RubraAudio.engine.silence();return true})()");
  const audio=await run("(async()=>{const out=[];for(const p of RubraMenuMusic.pieces){const c=new OfflineAudioContext(1,66150,22050),a=new RubraAudio.Engine(c);a.setOptions({music:true,sound:false,musicVolume:.45,effectsVolume:0});let t=.03;for(let i=64;i<72;i++){for(const e of RubraMenuMusic.events(p,i))a.tone(e.note,t+e.delay,e.duration,e.type,e.volume,'music',e.slide,e.envelope);t+=30/p.bpm;}const bounded=a.voices.size<=C.audio.maxVoices,b=await c.startRendering(),data=b.getChannelData(0);let energy=0,peak=0;for(const x of data){if(!Number.isFinite(x))throw Error('Nonfinite audio');energy+=x*x;peak=Math.max(peak,Math.abs(x));}a.dispose();out.push({id:p.id,duration:p.duration,energy,peak,bounded,voices:a.voices.size});}return out})()");
  assert.ok(audio.every(v=>v.energy>.01&&v.peak<.9&&v.bounded&&v.voices===0));assert.equal(new Set(audio.map(v=>v.energy.toFixed(5))).size,9);checks.push('nine actual offline audio renders are distinct, non-silent and unclipped');
  await check('five weapon cutouts contain genuine alpha and detailed silhouettes',"['frostbolt','halo','comet','glaive','blizzard'].every(id=>{const c=RubraProfane.weaponImages[id],d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let z=0,solid=0;const colors=new Set();for(let i=0;i<d.length;i+=4){z+=d[i+3]===0;solid+=d[i+3]>200;if(d[i+3]>200)colors.add(d[i]+','+d[i+1]+','+d[i+2]);}return z>d.length/4*.15&&solid>1000&&colors.size>100&&RubraWeaponArt.iconHtml(id).includes('data:image/png')})");
  await check('combat renderers consume the new projectile, orbit and storm textures',"(()=>{const c=document.createElement('canvas');c.width=c.height=256;const q=c.getContext('2d'),draw=q.drawImage.bind(q),seen=new Set();q.drawImage=(im,...args)=>{seen.add(im);draw(im,...args)};for(const [weapon,kind]of [['frostbolt','aimed'],['glaive','returning'],['comet','explosive']])RubraWeaponArt.shot(q,{weapon,kind,x:128,y:128,vx:100,vy:0,life:1});RubraWeaponArt.orbit(q,{id:'halo'},{x:128,y:128},1,K.stats({id:'halo',level:1}));RubraWeaponArt.effect(q,{weapon:'blizzard',kind:'storm',x:128,y:128,r:60,life:2,max:3,color:'#aaffff'},1);return ['frostbolt','halo','comet','glaive','blizzard'].every(id=>seen.has(RubraProfane.weaponImages[id]))})()");
  const sheet=await run("(()=>{const c=document.createElement('canvas');c.width=1250;c.height=460;const q=c.getContext('2d');q.fillStyle='#160b24';q.fillRect(0,0,c.width,c.height);q.imageSmoothingEnabled=false;['frostbolt','halo','comet','glaive','blizzard'].forEach((id,i)=>{const im=RubraProfane.weaponImages[id],s=Math.min(205/im.width,320/im.height);q.drawImage(im,i*250+125-im.width*s/2,20,im.width*s,im.height*s);RubraWeaponArt.item(q,id,i*250+125,395,0,2);q.fillStyle='#efcf82';q.font='16px sans-serif';q.fillText(C.weapons[id].name,i*250+20,450);});return c.toDataURL()})()");fs.writeFileSync(path.join(out,'weapons-dark.png'),Buffer.from(sheet.split(',')[1],'base64'));
  await check('tutorial retains original enemy health, speed and spawn cadence',"(()=>{save=K.defaults();begin();const e=newEnemy('vamp',map.spawn);state='paused';const p=K.encounter('tutorial',0,true);return e.maxHp===C.enemies.vamp.hp&&e.speed===C.enemies.vamp.speed&&p.count===1&&p.interval===C.combat.bossSpawnMultiplier&&p.hp===1&&p.bossHp===1})()");
  const pressure=await run("(()=>{const out=[];for(const id of ['necropolis','ice','profane']){const m=C.maps[id];let before=0,after=0;for(let t=0;t<m.bossAt;t+=.1){const phase=m.waves?[...m.waves].reverse().find(w=>t>=w.at):null,interval=phase?phase.interval:Math.max(m.minInterval,m.spawnInterval-t/m.bossAt*C.combat.spawnAcceleration),p=K.encounter(id,t);before+=.1/interval;after+=.1/interval*p.count/p.interval;}out.push({map:id,previous:Math.round(before),current:Math.round(after),ratio:after/before});}return out})()");assert.ok(pressure.every(p=>p.map==='profane'?p.ratio>4&&p.ratio<6:p.ratio>.8&&p.ratio<1.4));checks.push('spawn pressure rises in each combat chapter, with no global cap increase');
  await check('actual late encounter spawns groups safely and enforces the enemy cap',"(()=>{save.characters=Object.keys(C.characters);save.maps=Object.keys(C.maps);save.weapons=Object.keys(C.weapons);save.selectedMap='ice';save.selectedCharacter='aelthir';begin();elapsed=220;spawnClock=0;player.invuln=100;update(.01);const group=enemies.filter(e=>e.key!=='iceElite');if(group.length!==2||!group.every(e=>K.validPoint(e,map,e.r)&&e.maxHp>C.enemies[e.key].hp))return false;for(let i=0;i<200;i++)spawnMob('frostguard');state='paused';return enemies.length===K.enemyLimit(run.map)})()");
  await check('application title is RUBRA and stable save keys remain intact',"document.title==='RUBRA'&&C.profiles.campaign==='rubra-save-v2'");
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,audio,pressure,errors},null,2));console.log(checks.length+' music/update checks passed');app.exit(0);
 }catch(e){console.error(e);fs.writeFileSync(path.join(out,'failure.txt'),e.stack+'\n'+errors.join('\n'));app.exit(1);}
});
