// Launch the actual distribution executable and click through its real main window.
// No renderer harness and no changes to the player's RUBRA profile.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{spawn}=require('child_process');
const exe=path.resolve(process.argv.find(a=>a.startsWith('--exe='))?.slice(6)||'dist/RUBRA-Windows-x64.exe');
const profile=path.resolve('.test-profile/portable-'+Date.now()),output=path.resolve('test-output/portable');fs.mkdirSync(profile,{recursive:true});fs.mkdirSync(output,{recursive:true});
const wait=ms=>new Promise(r=>setTimeout(r,ms)),checks=[];let active;
async function launch(){
 const net=require('net'),server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));
 const child=spawn(exe,['--user-data-dir='+profile,'--remote-debugging-port='+port],{windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';child.stderr.on('data',b=>log+=b.toString());child.on('error',e=>log+=e.stack);let target;
 for(let i=0;i<160;i++){try{target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(t=>t.type==='page'&&t.url.startsWith('file:'));if(target)break;}catch{}await wait(250);}assert.ok(target,'Distribution window did not open: '+log);
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});let seq=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);else if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')errors.push(m.params.args.map(a=>a.description||a.value).join(' '));});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout: '+method));},20000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});
 const run=async code=>{const r=await call('Runtime.evaluate',{expression:'(()=>eval('+JSON.stringify(code)+'))()',returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 const ready=async()=>{for(let i=0;i<200;i++){if(await run("document.body?.dataset.assets==='ready'")){assert.deepEqual(errors,[]);return;}if(await run("document.body?.dataset.assets==='failed'"))throw Error(await run("document.getElementById('saveNotice').textContent"));if(errors.length)throw Error(errors.join('\n'));await wait(100);}throw Error('Assets never became ready');};
 const click=async selector=>{const p=await run(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled)throw Error('Missing/disabled control: '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,h=document.elementFromPoint(x,y);if(!(h===e||e.contains(h)))throw Error('Control obstructed');return {x,y};})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});await wait(100);};
 await call('Runtime.enable');await ready();assert.ok(fs.existsSync(path.join(profile,'Local Storage')),'Explicit isolated profile was not used');
 return {run,ready,click,errors,call,async close(){ws.send(JSON.stringify({id:++seq,method:'Browser.close'}));ws.close();for(let i=0;i<80&&child.exitCode===null;i++)await wait(100);assert.notEqual(child.exitCode,null,'Portable launcher did not close');}};
}
(async()=>{active=await launch();const check=async(name,code)=>{assert.ok(await active.run(code),name);checks.push(name);console.log('PASS '+name);};
 await check('actual EXE opens and enables Play/Arsenal',"assetReady&&!$('startButton').disabled&&!$('armoryButton').disabled&&save.selectedMap==='tutorial'");
 await active.run("const s=K.defaults();s.characters=Object.keys(C.characters);s.maps=Object.keys(C.maps);s.weapons=Object.keys(C.weapons);s.gold=1743;s.selectedCharacter='vespera';s.selectedMap='profane';K.persist(localStorage,s,C.profiles.campaign)");await active.close();active=await launch();
 await check('actual process restart with Profane campaign preserves progress and finishes loading',"assetReady&&save.gold===1743&&save.selectedMap==='profane'&&save.selectedCharacter==='vespera'");
 await active.click('#startButton');await active.run('render()');await check('physical Play click opens all visible hero portraits',"state==='characters'&&[...document.querySelectorAll('[data-portrait]')].length===Object.keys(C.characters).length&&[...document.querySelectorAll('[data-portrait]')].every(c=>c.getContext('2d').getImageData(0,0,64,64).data.some((v,i)=>i%4===3&&v))");
 await active.click('#charactersBack');await active.click('#armoryButton');await check('physical Arsenal click opens weapon catalogue',"state==='armory'&&$('armoryCards').children.length===Object.keys(C.weapons).length");await active.click('#armoryBack');
 await active.click('#optionsButton');await active.click('#openLaboratory');await active.click('#labUnlockAll');await active.click('#labPlay');await active.run('render()');await check('laboratory portraits load and campaign remains unchanged',"profile==='laboratory'&&state==='characters'&&C.profane.heroes.every(id=>{const c=document.querySelector('[data-portrait='+id+']');return c.getContext('2d').getImageData(0,0,64,64).data.some((v,i)=>i%4===3&&v)})&&K.load(localStorage,C.profiles.campaign).gold===1743");
 await active.click('#charactersNext');await active.click('[data-map=profane]');await active.click('#beginRun');await check('actual EXE starts Profane combat with prepared artwork',"state==='playing'&&map===C.maps.profane&&assetReady&&K.validPoint(player,map,player.r)");
 await active.run("player.invuln=0;player.dash=0;damagePlayer(999)");await check('defeat screen and retry remain functional',"state==='gameover'&&$('end').classList.contains('defeat-screen')");await active.click('#retryButton');await check('retry starts a fresh match',"state==='playing'&&run.gold===0");await active.run('finish(false,\'abandon\')');await active.click('#endMenuButton');
 const shot=await active.call('Page.captureScreenshot');fs.writeFileSync(path.join(output,'actual-executable.png'),Buffer.from(shot.data,'base64'));assert.deepEqual(active.errors,[]);await active.close();active=null;fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({exe,profile,checks,errors:[]},null,2));console.log(checks.length+' actual distribution checks passed');
})().catch(async e=>{console.error(e);fs.writeFileSync(path.join(output,'failure.txt'),e.stack);if(active)try{await active.close();}catch{}process.exitCode=1;});
