const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve('.test-profile/update-110'));app.disableHardwareAcceleration();
const output=path.resolve('test-output/update-110');fs.mkdirSync(output,{recursive:true});
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1360,height:900,webPreferences:{offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}}),errors=[],checks=[];win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});const run=c=>win.webContents.executeJavaScript('(()=>eval('+JSON.stringify(c)+'))()',true),wait=ms=>new Promise(r=>setTimeout(r,ms)),check=async(n,c)=>{assert.ok(await run(c),n);checks.push(n);console.log('PASS '+n)},shot=async n=>{await wait(300);fs.writeFileSync(path.join(output,n+'.png'),(await win.webContents.capturePage()).toPNG());};
try{await win.loadFile(path.resolve(process.argv.includes('--packaged')?'dist/win-unpacked/resources/app.asar/index.html':'index.html'));for(let i=0;i<200&&!await run('assetReady');i++)await wait(100);
await run("profile='laboratory';save=K.defaults();K.laboratoryUnlock(save,profile,'maps',Object.keys(C.maps));K.laboratoryUnlock(save,profile,'characters',Object.keys(C.characters));K.laboratoryUnlock(save,profile,'weapons',Object.keys(C.weapons));save.options.testArsenal=false;save.selectedMap='profane';save.selectedCharacter='malthor';begin();state='paused';");
await check('reported pillar shafts and bottom wall are solid',"[[472,600],[435,725],[1107,715],[245,930],[1200,940],[100,270]].every(([x,y])=>!K.validPoint({x:x*2.5,y:y*2.5},map,8))");
await check('central altar approaches and four main aisles remain accessible',"[[768,760],[768,620],[690,510],[900,490],[240,490],[1300,490],[768,260]].every(([x,y])=>K.validPoint({x:x*2.5,y:y*2.5},map,10))");
await check('dash and ghost cannot pass boundary masonry',"const o=map.obstacles.find(o=>o.kind==='wall'&&o.x===190&&o.y===2250),p={x:600,y:2200,r:8};moveBody(p,0,400);const ghost={x:600,y:2200,r:8,cfg:{ghost:true}};moveBody(ghost,0,400);p.y<2250&&ghost.y<2250");
await check('all walkable courtyard regions connect to the spawn',"(()=>{const step=30,b=map.bounds,nx=Math.ceil(b.w/step),ny=Math.ceil(b.h/step),good=new Set();for(let j=0;j<ny;j++)for(let i=0;i<nx;i++)if(K.validPoint({x:b.x+i*step,y:b.y+j*step},map,10))good.add(j*nx+i);const start=[...good].reduce((a,k)=>{const d=k=>Math.hypot(b.x+k%nx*step-map.spawn.x,b.y+Math.floor(k/nx)*step-map.spawn.y);return d(k)<d(a)?k:a}),seen=new Set([start]),queue=[start];for(let q=0;q<queue.length;q++){const k=queue[q];for(const n of [k-1,k+1,k-nx,k+nx])if(good.has(n)&&!seen.has(n)){const a={x:b.x+k%nx*step,y:b.y+Math.floor(k/nx)*step},z={x:b.x+n%nx*step,y:b.y+Math.floor(n/nx)*step};if(Math.hypot(z.x-a.x,z.y-a.y)>step+1||!K.clearSegment(a,z,map,10))continue;seen.add(n);queue.push(n);}}return seen.size/good.size>.99})()");
await run('charactersScreen()');await wait(100);await run("document.querySelector('[data-character=rubra]').click()");await wait(100);
for(const [w,h]of [[1360,900],[960,640],[420,850]]){win.setSize(w,h);await wait(150);await run("charactersScreen();document.querySelector('[data-character=rubra]').click();");await wait(150);await check('selected information visible without scrolling at '+w,"(()=>{const r=$('characterInfo').getBoundingClientRect(),a=$('charactersNext').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&a.bottom<=innerHeight&&$('characterInfo').textContent.includes('Rubra')&&document.documentElement.scrollWidth<=innerWidth})()");await shot(w+'-characters');await run("save.selectedCharacter='vespera';begin();togglePause()");await check('pause actions and summary at '+w,"state==='paused'&&document.body.classList.contains('in-menus')&&$('pauseSummary').textContent.includes('Vespera')");await shot(w+'-pause');await run("togglePause();run.xp=10000;levelUp()");await check('upgrade damage matches combat stats at '+w,"[...$('levelChoices').children].every((b,i)=>!C.weapons[offered[i].id]||b.querySelector('.choice-damage').innerHTML===weaponChoiceDetails(offered[i]))");await shot(w+'-upgrade');await run("chooseLevel(offered[0]);finish(false,'abandon');menu()");}
await check('red framed actions have one decorative arrow and no text arrow',"[...document.querySelectorAll('.menu-screen .primary')].every(b=>!/[→▶]/.test(b.textContent)&&getComputedStyle(b,'::after').backgroundImage.includes('arrow-gold.svg'))");
win.setSize(1360,900);await run("save.selectedCharacter='malthor';begin();state='paused';");
await check('boss aimed volley and enraged telegraph remain readable',"(()=>{const boss=newEnemy('boss',{x:player.x+70,y:player.y},true);enemies=[boss];enemyAttack(boss);enemyAttack(boss);const t=boss.telegraph;shots=[];releaseAttack(boss,t);const aimed=shots.length===13;boss.hp=boss.maxHp*.4;enemyAttack(boss);return aimed&&boss.telegraph.time>=.8&&boss.telegraph.count===12})()");
const benchmark=await run("(()=>{const out=[];for(const id of ['malthor','vespera']){save.selectedCharacter=id;begin();run.weapons=['execution','bloodwhip','rosary','absolute','verdict','censer'].map(id=>({id,level:7}));run.gargoyleSpawned=true;run.bossSpawned=true;elapsed=540;spawnClock=1e9;player.x=1920;player.y=1800;const boss=newEnemy('boss',{x:1980,y:1800},true);boss.action=1e9;enemies=[boss];let seconds=0;for(;seconds<180&&state==='playing';seconds+=1/30){player.invuln=100;boss.x=1980;boss.y=1800;update(1/30);}out.push({hero:id,seconds:Math.round(seconds*10)/10,won:state==='victory'});}return out})()");console.log(JSON.stringify(benchmark));assert.ok(benchmark.every(b=>b.won&&b.seconds>=20&&b.seconds<150),'Perfect-contact full arsenal should take a sustained fight');checks.push('maximum-level perfect-contact boss benchmark');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,benchmark,errors},null,2));console.log(checks.length+' update checks passed');app.exit(0);
}catch(e){console.error(e);fs.writeFileSync(path.join(output,'failure.txt'),e.stack+'\n'+errors.join('\n'));app.exit(1);}});
