'use strict';
const RubraCollections=(()=>{
 let back='options',tab='creatures',resultState='gameover';
 const fmt=n=>Math.round(n||0).toLocaleString('pt-BR');
 const sceneNames={menu:'Menu inicial',characters:'Caçadores',maps:'Destinos'};
 const lore={tutorial:'O bosque guarda ecos dos primeiros caçadores. Vhalkar protege o limiar entre a mata e a noite.',necropolis:'Sob as lápides, juramentos antigos ainda movem os mortos. Morthar vigia as almas que não partiram.',ice:'A geada preserva guerreiros e suas últimas promessas. Skarn carrega o coração imóvel deste inverno.',profane:'No claustro, a fé se tornou penitência. O Inquisidor exige obediência até dos que já morreram.'};
 function portrait(canvas,cfg,boss){const q=canvas.getContext('2d');q.imageSmoothingEnabled=false;const im=RubraProfane.enemyFrames[cfg.asset]?.[0]||assetImages[cfg.asset]||spriteImage(boss?'boss':cfg.sprite||'shade');const s=Math.min(110/im.width,112/im.height);q.drawImage(im,Math.round((128-im.width*s)/2),Math.round(122-im.height*s),Math.round(im.width*s),Math.round(im.height*s));}
 function book(){screen('bestiary');wallet();const box=$('bestiaryCards');box.replaceChildren();$('showCreatures').setAttribute('aria-pressed',String(tab==='creatures'));$('showRelics').setAttribute('aria-pressed',String(tab==='relics'));
  if(tab==='relics'){const relics=['lance','absolute','verdict'];$('bestiarySummary').textContent='Relíquias dos guardiões · a coleção acompanha seus desbloqueios existentes.';for(const id of relics){const owned=save.weapons.includes(id),w=C.weapons[id],card=document.createElement('article');card.className='archive-card';card.innerHTML=RubraWeaponArt.iconHtml(id)+'<h3>'+w.name+'</h3><strong>'+(owned?'NA COLEÇÃO':'AINDA SELADA')+'</strong><p>'+w.description+'</p><p>'+w.unlock+'</p>';box.append(card);}return;}
  const rows=[];for(const [mapId,m]of Object.entries(C.maps)){const keys=[...new Set([...m.enemies,...(m.waves||[]).flatMap(w=>w.pool),...(m.eliteEvery?[m.elite||'elite']:[]),...(mapId==='profane'?['profaneGargoyle']:[])])];for(const id of keys)rows.push({id,cfg:C.enemies[id],mapId});rows.push({id:'boss:'+mapId,cfg:m.boss,mapId,boss:true});}
  $('bestiarySummary').textContent=rows.filter(v=>save.bestiary[v.id]>0).length+' / '+rows.length+' registros descobertos · '+(profile==='laboratory'?'Laboratório — coleção separada':'Campanha')+'. Eliminações registradas a partir da versão 1.14.';
  for(const {id,cfg,mapId,boss}of rows){const count=save.bestiary[id]||0,card=document.createElement('article');card.className='archive-card';const behavior=boss?'Guardião: observe os avisos e alterne ataque e esquiva.':cfg.miniBoss?'Investidas e impacto circular. Saia do círculo antes do golpe.':cfg.behavior==='ranged'?'Mantém distância e dispara projéteis.':mapId==='profane'?'Persegue e prepara investidas físicas. Resiste à lentidão contínua.':'Persegue o caçador e causa dano por contato.';
   card.innerHTML='<canvas width="128" height="128" aria-label="'+(count?cfg.name:'Criatura desconhecida')+'"></canvas><small>'+C.maps[mapId].name+'</small><h3>'+(count?cfg.name:'Registro não descoberto')+'</h3><strong>'+fmt(count)+' eliminações</strong><p>'+(count?behavior:'Derrote esta criatura para revelar sua arte e comportamento.')+'</p><p>'+(boss?(count>=3?lore[mapId]:count?'Uma presença governa estas terras. Vença este guardião três vezes para completar sua história.':'História selada · primeira vitória revela o guardião.'):(count>=10?lore[mapId]:'História da região: '+Math.min(count,10)+'/10 eliminações.'))+'</p>';box.append(card);if(count)portrait(card.querySelector('canvas'),cfg,boss);else{const q=card.querySelector('canvas').getContext('2d');q.fillStyle='#bba083';q.font='64px serif';q.fillText('?',48,90);}}
 }
 function openBook(){back=state;tab='creatures';book();}
 function music(){screen('musicLibrary');const box=$('musicCards');box.replaceChildren();RubraAudio.unlock();if(RubraAudio.engine)RubraAudio.engine.libraryScene=['characters','maps'].includes(menuReturn)?menuReturn:'menu';for(const [scene,list]of Object.entries(RubraMenuMusic.playlists))for(const track of list){const card=document.createElement('article');card.className='archive-card';card.innerHTML='<small>'+sceneNames[scene]+'</small><h3>'+track.title+'</h3><p>'+formatTime(track.duration||track.steps*30/track.bpm)+' · '+track.bpm+' BPM</p>';const b=document.createElement('button');b.className='primary';b.textContent='Tocar agora';b.dataset.track=track.id;b.onclick=()=>{RubraAudio.unlock();if(!RubraAudio.engine?.selectTrack(track.id))return;save.options.music=true;globalThis.RubraPreferences=save.options;$('musicOption').checked=true;storeSave();status();};card.append(b);box.append(card);}status();}
 function status(){const e=RubraAudio.engine,t=e?.currentTrack;$('musicStatus').textContent=e?.manual?'Escolha manual: '+t?.title:'Seleção automática por menu';for(const b of document.querySelectorAll('[data-track]')){const chosen=b.dataset.track===e?.manual;b.setAttribute('aria-pressed',String(chosen));b.textContent=chosen?'Tocando agora':'Tocar agora';}}
 function report(){resultState=state;const r=save.lastResult,stats=RubraChronicleCore.report(r?.report),box=$('reportContent');screen('report');const total=Object.values(stats.weapons).reduce((a,w)=>a+w.damage,0);box.innerHTML='<div class="report-totals"><span>Tempo <b>'+formatTime(r.elapsed)+'</b></span><span>Eliminações <b>'+fmt(r.kills)+'</b></span><span>Dano causado <b>'+fmt(total)+'</b></span><span>Dano recebido <b>'+fmt(stats.damageTaken)+' corações</b></span></div><p>Dano efetivo, limitado à vida restante do alvo. Objetivos destrutíveis não entram no dano de combate.</p><div class="report-table"><table><thead><tr><th>Arma</th><th>Dano</th><th>Eliminações</th><th>Nível final</th></tr></thead><tbody></tbody></table></div><h3>Melhorias durante a expedição</h3><ol class="report-history"></ol><h3>Objetivos opcionais</h3><div class="report-events"></div>';
  const ids=[...new Set([...(r.weapons||[]).map(w=>w.id),...Object.keys(stats.weapons)])];for(const id of ids){const s=stats.weapons[id]||{},tr=document.createElement('tr');tr.innerHTML='<td>'+(C.weapons[id]?.name||'Habilidade do caçador')+'</td><td>'+fmt(s.damage)+'</td><td>'+fmt(s.kills)+'</td><td>'+((r.weapons||[]).find(w=>w.id===id)?.level||'—')+'</td>';box.querySelector('tbody').append(tr);}for(const h of stats.history){const li=document.createElement('li');li.textContent=formatTime(h.at)+' · '+C.weapons[h.id].name+' · Nv. '+h.level;box.querySelector('ol').append(li);}if(!stats.history.length)box.querySelector('ol').textContent='Nenhuma melhoria registrada.';box.querySelector('.report-events').textContent=stats.events.length?stats.events.map(e=>RubraChronicles.names[e.type]+' · '+(e.won?'concluído, +'+e.gold+' ouro':'não concluído')).join(' / '):'Nenhum objetivo concluído ou encerrado nesta expedição.';
 }
 $('openBestiary').onclick=openBook;$('armoryBestiary').onclick=openBook;$('showCreatures').onclick=()=>{tab='creatures';book();};$('showRelics').onclick=()=>{tab='relics';book();};$('bestiaryBack').onclick=()=>screen(back);
 $('openMusicLibrary').onclick=music;$('musicBack').onclick=()=>{screen('options');$('musicOption').checked=save.options.music;};$('musicAutomatic').onclick=()=>{RubraAudio.engine?.automatic();status();};$('openReport').onclick=report;$('reportBack').onclick=()=>{screen('end');state=resultState;};
 document.addEventListener('visibilitychange',status);
 return {book,music,report,status};
})();

globalThis.RubraCollections=RubraCollections;
