(function(root){
const C=root.RubraConfig||(typeof require==='function'?require('./config.js'):null);
const integer=(v,max=1000000000)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
const unique=(a,table)=>[...new Set(Array.isArray(a)?a.filter(x=>Object.hasOwn(table,x)):[])];
function defaults(){return {version:3,gold:0,best:0,selectedCharacter:'rubra',selectedMap:'tutorial',characters:['rubra'],completedMaps:[],maps:['tutorial'],weapons:['blade'],options:{sound:true,music:true,musicVolume:C.audio.musicVolume,effectsVolume:C.audio.effectsVolume,particles:true},active:null,lastResult:null};}
function validPoint(p,map,r=8){const b=map.bounds;if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y))return false;return p.x-r>=b.x&&p.y-r>=b.y&&p.x+r<=b.x+b.w&&p.y+r<=b.y+b.h&&!map.obstacles.some(o=>Math.hypot(p.x-o.x,p.y-o.y)<r+o.r);}
function freePoint(map,away=null,minDistance=0,r=14,random=Math.random){const b=map.bounds;for(let i=0;i<180;i++){const p={x:b.x+r+random()*(b.w-2*r),y:b.y+r+random()*(b.h-2*r)};if(validPoint(p,map,r)&&(!away||Math.hypot(p.x-away.x,p.y-away.y)>=minDistance))return p;}for(let y=b.y+r;y<b.y+b.h-r;y+=25)for(let x=b.x+r;x<b.x+b.w-r;x+=25){const p={x,y};if(validPoint(p,map,r)&&(!away||Math.hypot(x-away.x,y-away.y)>=minDistance))return p;}return null;}
function spawnPoint(map,player,minDistance,r,random=Math.random){if(!map.world)return freePoint(map,player,minDistance,r,random);const outer=map.world.spawnOuter;for(let i=0;i<180;i++){const a=random()*Math.PI*2,d=minDistance+random()*(outer-minDistance),p={x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d};if(validPoint(p,map,r))return p;}return null;}
function migrate(input,legacy=0){const s=defaults();if(!input||typeof input!=='object')input={};s.characters=unique([...s.characters,...(input.version===2?['rubra','noctis']:Array.isArray(input.characters)?input.characters:[])],C.characters);s.completedMaps=unique(input.completedMaps,C.maps);s.gold=integer(input.gold);s.best=Math.max(integer(input.best),integer(Number(legacy)));s.maps=unique([...s.maps,...(Array.isArray(input.maps)?input.maps:[])],C.maps);s.weapons=unique([...s.weapons,...(Array.isArray(input.weapons)?input.weapons:[])],C.weapons);if(s.characters.includes(input.selectedCharacter))s.selectedCharacter=input.selectedCharacter;if(input.version===2&&!s.maps.includes('necropolis'))s.maps.push('necropolis');if(s.maps.includes(input.selectedMap))s.selectedMap=input.selectedMap;if(input.version===2){s.maps=unique([...s.maps,'necropolis'],C.maps);s.weapons=unique([...s.weapons,'dagger'],C.weapons);}s.options.sound=typeof input.options?.sound==='boolean'?input.options.sound:true;s.options.music=typeof input.options?.music==='boolean'?input.options.music:s.options.sound;for(const key of ['musicVolume','effectsVolume'])s.options[key]=Number.isFinite(input.options?.[key])?Math.max(0,Math.min(1,input.options[key])):C.audio[key];s.options.particles=input.options?.particles!==false;if(typeof input.options?.testArsenal==='boolean')s.options.testArsenal=input.options.testArsenal;
 if(input.lastResult&&typeof input.lastResult.id==='string')s.lastResult={...input.lastResult,gold:integer(input.lastResult.gold),kills:integer(input.lastResult.kills)};
 if(input.active&&typeof input.active.id==='string'&&s.maps.includes(input.active.map)&&s.characters.includes(input.active.character)){
  const a=input.active;s.active={...a,gold:integer(a.gold),kills:integer(a.kills),elapsed:Math.min(36000,Math.max(0,Number(a.elapsed)||0)),level:Math.max(1,integer(a.level,999)),xp:integer(a.xp),bossSpawned:a.bossSpawned===true,bossKilled:a.bossKilled===true};
  s.active.weapons=(Array.isArray(a.weapons)?a.weapons:[]).filter(w=>w&&(s.weapons.includes(w.id)||C.characters[a.character].weapon===w.id)).filter((w,i,arr)=>arr.findIndex(v=>v.id===w.id)===i).slice(0,C.slots).map(w=>({id:w.id,level:Math.max(1,integer(w.level,weaponCap(a.map,w.id)))}));
  if(!s.active.weapons.length)s.active.weapons=[{id:C.characters[a.character].weapon,level:1}];
  if(!validPoint(a.player,C.maps[a.map],C.characters[a.character].radius))s.active.player={...C.maps[a.map].spawn,hp:C.characters[a.character].hp};
 }
 grantIceChapter(s);grantProfaneChapter(s);return s;}
function load(storage,key='rubra-save-v2'){let obj;try{obj=JSON.parse(storage.getItem(key)||'null');}catch{try{const raw=storage.getItem(key);if(raw)storage.setItem(key+'-unreadable-backup',raw);}catch{}}return migrate(obj,key===C.profiles.campaign?storage.getItem('rubra-best'):0);}
function persist(storage,save,key='rubra-save-v2'){storage.setItem(key,JSON.stringify(save));}
function settle(save,run,outcome){if(!run||save.lastResult?.id===run.id)return false;if(save.active?.id!==run.id)return false;save.gold=integer(save.gold+integer(run.gold));save.best=Math.max(save.best,integer(run.kills));save.lastResult={id:run.id,gold:integer(run.gold),kills:integer(run.kills),outcome,elapsed:run.elapsed,map:run.map};save.active=null;return true;}
function choices(run,save,random=Math.random){const list=[];for(const [id,w]of Object.entries(C.weapons)){if((!save.weapons.includes(id)&&C.characters[run.character]?.weapon!==id)||(!run.weapons.some(v=>v.id===id)&&!allowedWeapon(run.map,id,run.character)))continue;const slot=run.weapons.find(v=>v.id===id);if(slot&&slot.level<weaponCap(run.map,id))list.push({kind:'weapon',id,level:slot.level+1});else if(!slot&&run.weapons.length<C.slots)list.push({kind:'weapon',id,level:1});}for(let i=list.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list.length?list.slice(0,3):[{kind:'heal',id:'heal'},{kind:'gold',id:'gold'}];}
function upgrade(run,save,choice){if(choice.kind==='weapon'){const w=C.weapons[choice.id];if(!w||(!save.weapons.includes(choice.id)&&C.characters[run.character]?.weapon!==choice.id)||(!run.weapons.some(v=>v.id===choice.id)&&!allowedWeapon(run.map,choice.id,run.character)))return false;const slot=run.weapons.find(v=>v.id===choice.id);if(slot){if(slot.level>=weaponCap(run.map,choice.id))return false;slot.level++;}else{if(run.weapons.length>=C.slots)return false;run.weapons.push({id:choice.id,level:1});}return true;}if(choice.kind==='gold'){run.gold=integer(run.gold+C.economy.fallbackGold);return true;}if(choice.kind==='heal')return true;return false;}
function stats(slot,mod={}){const w=C.weapons[slot.id],n=slot.level-1;return {...w,damage:w.damage*(1+n*w.growth.damage)*(mod.damage||1),interval:w.interval*(1-n*w.growth.interval)/(mod.attackSpeed||1),range:w.range*(1+n*w.growth.range)*(mod.range||1),radius:(w.radius||0)*(1+n*.12)*(mod.range||1),count:w.count+(n>=2?1:0)+(n>=4?1:0)};}
function hit(target,amount,onDeath){if(target.dead||!Number.isFinite(amount)||amount<=0)return false;target.hp=Math.max(0,target.hp-amount);if(target.hp===0){target.dead=true;onDeath(target);}return true;}
function allowedWeapon(map,id,character){return !!C.weapons[id]&&(!map||!!C.maps[map]?.weapons.includes(id)||C.characters[character]?.weapon===id);}
function startWeapon(character,map){const id=C.characters[character].weapon;return allowedWeapon(map,id,character)?id:(C.maps[map]?.startWeapon||'blade');}
function unlock(save,run){const got=[];const add=id=>{if(!save.weapons.includes(id)){save.weapons.push(id);got.push(id);}};
 if(run.map==='tutorial'){if(run.elapsed>=C.weapons.acorn.unlockSeconds)add('acorn');if(run.bossKilled){if(!save.completedMaps.includes('tutorial'))save.completedMaps.push('tutorial');if(!save.maps.includes('necropolis'))save.maps.push('necropolis');if(!save.characters.includes('noctis'))save.characters.push('noctis');add('dagger');}}
 if(run.map==='necropolis'){add('dagger');for(const id of ['cinder','chain','reaper'])if(run.elapsed>=C.weapons[id].unlockSeconds)add(id);if(run.elapsed>=C.weapons.ember.unlockSeconds)add('ember');if(run.elapsed>=C.weapons.thorns.unlockSeconds)add('thorns');if(run.bossKilled){add('lance');if(!save.completedMaps.includes('necropolis'))save.completedMaps.push('necropolis');}}grantIceChapter(save);if(run.map==='ice'){for(const id of C.ice.weapons)if(run.elapsed>=C.weapons[id].unlockSeconds)add(id);if(run.bossKilled){add(C.ice.bossWeapon);if(!save.completedMaps.includes('ice'))save.completedMaps.push('ice');}}if(run.map==='profane'){for(const id of C.profane.weapons){const w=C.weapons[id];if(w.unlockSeconds&&run.elapsed>=w.unlockSeconds)add(id);}if(run.bossKilled){add(C.profane.bossWeapon);if(!save.completedMaps.includes('profane'))save.completedMaps.push('profane');}}grantProfaneChapter(save);return got;}
// Public offline testing feature. Profile isolation, not authentication.
function laboratoryUnlock(save,profile,type,ids){if(profile!=='laboratory'||!['characters','maps','weapons'].includes(type))return false;const valid=unique(ids,C[type]);for(const id of valid)if(!save[type].includes(id)){save[type].push(id);if(type==='characters'&&C.characters[id].price&&!save.weapons.includes(C.characters[id].weapon))save.weapons.push(C.characters[id].weapon);}if(type==='maps'){grantIceChapter(save);grantProfaneChapter(save);}return valid.length>0;}
function laboratoryReset(save,profile){if(profile!=='laboratory')return false;if(save.active)settle(save,save.active,'abandon');const initial=defaults();for(const key of ['characters','maps','weapons','completedMaps','selectedCharacter','selectedMap'])save[key]=initial[key];return true;}
function weaponCap(map,id){return Math.min(C.weapons[id]?.maxLevel||1,C.maps[map]?.maxWeaponLevel||C.maxWeaponLevel);}
function purchaseCharacter(save,id){const c=C.characters[id];if(!c?.price||save.characters.includes(id)||!save.maps.includes(c.purchaseMap)||!Number.isInteger(save.gold)||save.gold<c.price)return false;save.gold-=c.price;save.characters.push(id);if(!save.weapons.includes(c.weapon))save.weapons.push(c.weapon);save.selectedCharacter=id;return true;}
function grantIceChapter(save){if(save.completedMaps.includes('ice')&&!save.weapons.includes(C.ice.bossWeapon))save.weapons.push(C.ice.bossWeapon);if(save.completedMaps.includes('necropolis')&&!save.maps.includes('ice'))save.maps.push('ice');if(!save.maps.includes('ice'))return;for(const id of C.ice.inherited.concat('frostbolt'))if(!save.weapons.includes(id))save.weapons.push(id);if(!save.characters.includes('nivor'))save.characters.push('nivor');}
function grantProfaneChapter(save){if(save.completedMaps.includes('ice')&&!save.maps.includes('profane'))save.maps.push('profane');if(save.completedMaps.includes('profane')&&!save.weapons.includes('verdict'))save.weapons.push('verdict');if(!save.maps.includes('profane'))return;if(!save.characters.includes('karn'))save.characters.push('karn');if(!save.weapons.includes('execution'))save.weapons.push('execution');}
function profaneWave(seconds){return [...C.maps.profane.waves].reverse().find(w=>seconds>=w.at)||C.maps.profane.waves[0];}
const api={grantProfaneChapter,profaneWave,grantIceChapter,weaponCap,purchaseCharacter,laboratoryReset,integer,defaults,migrate,load,persist,settle,choices,upgrade,stats,hit,validPoint,freePoint,spawnPoint,unlock,allowedWeapon,startWeapon,laboratoryUnlock};root.RubraCore=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
