(function(root){
const C=root.RubraConfig||(typeof require==='function'?require('./config.js'):null);
const integer=(v,max=1000000000)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
const unique=(a,table)=>[...new Set(Array.isArray(a)?a.filter(x=>Object.hasOwn(table,x)):[])];
function defaults(){return {version:2,gold:0,best:0,selectedCharacter:'noctis',selectedMap:'tutorial',maps:['tutorial','necropolis'],weapons:['blade','dagger'],options:{sound:false,particles:true},active:null,lastResult:null};}
function validPoint(p,map,r=8){const b=map.bounds;if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y))return false;return p.x-r>=b.x&&p.y-r>=b.y&&p.x+r<=b.x+b.w&&p.y+r<=b.y+b.h&&!map.obstacles.some(o=>Math.hypot(p.x-o.x,p.y-o.y)<r+o.r);}
function freePoint(map,away=null,minDistance=0,r=14,random=Math.random){const b=map.bounds;for(let i=0;i<180;i++){const p={x:b.x+r+random()*(b.w-2*r),y:b.y+r+random()*(b.h-2*r)};if(validPoint(p,map,r)&&(!away||Math.hypot(p.x-away.x,p.y-away.y)>=minDistance))return p;}for(let y=b.y+r;y<b.y+b.h-r;y+=25)for(let x=b.x+r;x<b.x+b.w-r;x+=25){const p={x,y};if(validPoint(p,map,r)&&(!away||Math.hypot(x-away.x,y-away.y)>=minDistance))return p;}return null;}
function migrate(input,legacy=0){const s=defaults();if(!input||typeof input!=='object')input={};s.gold=integer(input.gold);s.best=Math.max(integer(input.best),integer(Number(legacy)));s.maps=unique([...s.maps,...(Array.isArray(input.maps)?input.maps:[])],C.maps);s.weapons=unique([...s.weapons,...(Array.isArray(input.weapons)?input.weapons:[])],C.weapons);if(Object.hasOwn(C.characters,input.selectedCharacter))s.selectedCharacter=input.selectedCharacter;if(s.maps.includes(input.selectedMap))s.selectedMap=input.selectedMap;s.options.sound=input.options?.sound===true;s.options.particles=input.options?.particles!==false;
 if(input.lastResult&&typeof input.lastResult.id==='string')s.lastResult={...input.lastResult,gold:integer(input.lastResult.gold),kills:integer(input.lastResult.kills)};
 if(input.active&&typeof input.active.id==='string'&&Object.hasOwn(C.maps,input.active.map)&&Object.hasOwn(C.characters,input.active.character)){
  const a=input.active;s.active={...a,gold:integer(a.gold),kills:integer(a.kills),elapsed:Math.min(36000,Math.max(0,Number(a.elapsed)||0)),level:Math.max(1,integer(a.level,999)),xp:integer(a.xp),bossSpawned:a.bossSpawned===true,bossKilled:a.bossKilled===true};
  s.active.weapons=(Array.isArray(a.weapons)?a.weapons:[]).filter(w=>w&&s.weapons.includes(w.id)).filter((w,i,arr)=>arr.findIndex(v=>v.id===w.id)===i).slice(0,C.slots).map(w=>({id:w.id,level:Math.max(1,integer(w.level,C.weapons[w.id].maxLevel))}));
  if(!s.active.weapons.length)s.active.weapons=[{id:C.characters[a.character].weapon,level:1}];
  if(!validPoint(a.player,C.maps[a.map],C.characters[a.character].radius))s.active.player={...C.maps[a.map].spawn,hp:C.characters[a.character].hp};
 }
 return s;}
function load(storage,key='rubra-save-v2'){let obj;try{obj=JSON.parse(storage.getItem(key)||'null');}catch{try{const raw=storage.getItem(key);if(raw)storage.setItem(key+'-unreadable-backup',raw);}catch{}}return migrate(obj,storage.getItem('rubra-best'));}
function persist(storage,save,key='rubra-save-v2'){storage.setItem(key,JSON.stringify(save));}
function settle(save,run,outcome){if(!run||save.lastResult?.id===run.id)return false;if(save.active?.id!==run.id)return false;save.gold=integer(save.gold+integer(run.gold));save.best=Math.max(save.best,integer(run.kills));save.lastResult={id:run.id,gold:integer(run.gold),kills:integer(run.kills),outcome,elapsed:run.elapsed,map:run.map};save.active=null;return true;}
function choices(run,save,random=Math.random){const list=[];for(const [id,w]of Object.entries(C.weapons)){if(!save.weapons.includes(id))continue;const slot=run.weapons.find(v=>v.id===id);if(slot&&slot.level<w.maxLevel)list.push({kind:'weapon',id,level:slot.level+1});else if(!slot&&run.weapons.length<C.slots)list.push({kind:'weapon',id,level:1});}for(let i=list.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list.length?list.slice(0,3):[{kind:'heal',id:'heal'},{kind:'gold',id:'gold'}];}
function upgrade(run,save,choice){if(choice.kind==='weapon'){const w=C.weapons[choice.id];if(!w||!save.weapons.includes(choice.id))return false;const slot=run.weapons.find(v=>v.id===choice.id);if(slot){if(slot.level>=w.maxLevel)return false;slot.level++;}else{if(run.weapons.length>=C.slots)return false;run.weapons.push({id:choice.id,level:1});}return true;}if(choice.kind==='gold'){run.gold=integer(run.gold+C.economy.fallbackGold);return true;}if(choice.kind==='heal')return true;return false;}
function stats(slot,mod={}){const w=C.weapons[slot.id],n=slot.level-1;return {...w,damage:w.damage*(1+n*w.growth.damage)*(mod.damage||1),interval:w.interval*(1-n*w.growth.interval)/(mod.attackSpeed||1),range:w.range*(1+n*w.growth.range)*(mod.range||1),radius:(w.radius||0)*(1+n*.12)*(mod.range||1),count:w.count+(n>=2?1:0)+(n>=4?1:0)};}
function hit(target,amount,onDeath){if(target.dead||!Number.isFinite(amount)||amount<=0)return false;target.hp=Math.max(0,target.hp-amount);if(target.hp===0){target.dead=true;onDeath(target);}return true;}
function unlock(save,run){const got=[];const add=id=>{if(!save.weapons.includes(id)){save.weapons.push(id);got.push(id);}};if(run.map==='necropolis'){add('dagger');if(run.elapsed>=30)add('ember');if(run.elapsed>=60)add('thorns');if(run.bossKilled)add('lance');}return got;}
const api={integer,defaults,migrate,load,persist,settle,choices,upgrade,stats,hit,validPoint,freePoint,unlock};root.RubraCore=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
