'use strict';
const C=RubraConfig,K=RubraCore;
const original={render,reset,drawSprite,tree,pillar,makeGround,dash,beep};
let profile='campaign',characterFrames={},portraitFrames={};
let save=K.load(localStorage),run=null,map=C.maps.tutorial,shots=[],effects=[],loot=[],weaponClocks={},assetImages={},heroFrames={},assetReady=false,entityId=0,spawnClock=0,checkpointClock=0,eliteIndex=0,offered=[],saveError=false,menuReturn='menu';
globalThis.RubraPreferences=save.options;
const alive=()=>enemies.filter(e=>!e.dead);
const eligibleLoot=()=>loot.filter(d=>!d.collected);
const finite=(v,fallback)=>Number.isFinite(v)?v:fallback;
const safeId=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
function storeSave(){try{K.persist(localStorage,save,C.profiles[profile]);saveError=false;return true;}catch{saveError=true;$('saveNotice').textContent='Não foi possível salvar. Libere espaço ou permita armazenamento; mantenha a janela aberta.';return false;}}
function clearInput(){keys.clear();joystick={x:0,y:0};$('stick').style.transform='';}
function hideScreens(){for(const id of ['menu','characters','maps','options','upgrade','pause','end','help','laboratory'])$(id).classList.add('hidden');clearInput();}
function screen(id){hideScreens();state=id;$(id).classList.remove('hidden');setTimeout(()=>{if(state!==id)return;const target=$(id).querySelector('[aria-pressed=true]')||$(id).querySelector('button:not(:disabled),input:not(:disabled)');target?.focus({preventScroll:true});},0);}
function wallet(){$('profileBadge').textContent=profile==='laboratory'?'LABORATÓRIO · SAVE DE TESTES':'CAMPANHA';document.body.dataset.profile=profile;document.body.classList.toggle('reduce-decoration',!save.options.particles);for(const el of document.querySelectorAll('.goldTotal'))el.textContent=save.gold;$('totalGold').textContent=save.gold;$('record').textContent=String(save.best).padStart(3,'0');$('continueRun').classList.toggle('hidden',!save.active);$('startButton').textContent=save.active?'Nova expedição':'Jogar';}
function menu(){run=null;enemies=[];shots=[];effects=[];loot=[];projectiles=[];original.reset();map=C.maps[save.selectedMap];buildGround();screen('menu');for(const id of ['hud','runExtra','mobile','dashMeter','bossHud','toast'])$(id).classList.add('hidden');wallet();}
showMenu=menu;
function persistSelection(){storeSave();wallet();}
function charactersScreen(){screen('characters');wallet();$('characterCards').replaceChildren();
 for(const id of ['rubra','noctis']){const c=C.characters[id],available=save.characters.includes(id),b=document.createElement('button');b.className='select-card champion';b.dataset.character=id;b.setAttribute('aria-pressed',String(save.selectedCharacter===id));b.setAttribute('aria-disabled',String(!available));
 b.innerHTML=`<h3>${c.name}</h3><div class="champion-frame"><canvas class="portrait" width="64" height="64" data-portrait="${id}"></canvas><span class="champion-seal">${available?'◆':'BLOQUEADO'}</span></div><small>${available?(save.selectedCharacter===id?'✓ SELECIONADO':'Selecionar caçador'):'Vença Vhalkar no tutorial'}</small>`;
 b.onclick=()=>{if(available){save.selectedCharacter=id;persistSelection();charactersScreen();}else showCharacterInfo(id);};b.onfocus=()=>showCharacterInfo(id);$('characterCards').append(b);}
 showCharacterInfo(save.selectedCharacter);
}
function showCharacterInfo(id){const c=C.characters[id];$('characterInfo').innerHTML=`<strong>${c.name} · ${save.characters.includes(id)?'Disponível':'Bloqueado · conclua o tutorial'}</strong><p>${c.description}</p><div class="character-stats"><span>♥ VIDA <b>${c.hp}</b></span><span>VELOCIDADE <b>${c.speed}</b></span><span>DANO <b>×${c.damage}</b></span></div><p>Arma: ${C.weapons[c.weapon].name}<br>${c.passive}</p><small>${save.characters.includes(id)?'No tutorial, todos começam com a Lâmina ancestral.':c.unlock}</small>`;}
function mapsScreen(){screen('maps');$('mapCards').replaceChildren();for(const [id,m]of Object.entries(C.maps)){const b=document.createElement('button');b.className='select-card map-card';b.dataset.map=id;b.setAttribute('aria-pressed',String(save.selectedMap===id));b.disabled=!save.maps.includes(id);b.innerHTML=`<div class="map-preview ${id==='tutorial'?'tutorial':''}">${id==='necropolis'?'<img src="'+C.assets.path+'" class="map-preview" alt="Caminhos da Necrópole">':'<canvas width="220" height="85" class="map-preview" id="tutorialPreview"></canvas>'}</div><small>${m.subtitle}</small><h3>${m.name}</h3><p>${m.description}</p><small>Guardião: ${formatTime(m.bossAt)} · ${save.maps.includes(id)?'Disponível':'Bloqueado'}</small>`;b.onclick=()=>{save.selectedMap=id;persistSelection();mapsScreen();};$('mapCards').append(b);}const preview=$('tutorialPreview');if(preview){const pg=preview.getContext('2d');pg.imageSmoothingEnabled=false;const backup=map;map=C.maps.tutorial;buildGround();pg.drawImage(ground,0,0,220,85);map=backup;buildGround();}}
function buildGround(){ground.width=W;ground.height=H;g.imageSmoothingEnabled=false;scenery.length=0;if(map===C.maps.tutorial){original.makeGround();for(let x=15;x<W;x+=70){scenery.push({type:'tree',x,y:46,s:1});scenery.push({type:'tree',x,y:H+25,s:1.15});}for(const o of map.obstacles)scenery.push({type:'pillar',...o});return;}
 g.fillStyle='#191e29';g.fillRect(0,0,W,H);let n=941;for(let y=0;y<H;y+=6)for(let x=0;x<W;x+=6){n=(n*1664525+1013904223)>>>0;g.fillStyle=['#20242e','#242631','#292834','#242b32'][(n>>>16)%4];g.fillRect(x,y,6,6);}for(let i=0;i<950;i++){n=(n*1664525+1013904223)>>>0;const x=(n>>>8)%W;n=(n*1664525+1013904223)>>>0;const y=(n>>>8)%H;g.fillStyle=i%3?'#3c3340':'#45414a';g.fillRect(x,y,2,2);}if(assetImages.path)g.drawImage(assetImages.path,0,0,W,H);
 for(let x=12;x<W;x+=83){scenery.push({type:'tree',x,y:60,s:.36});scenery.push({type:'tree',x,y:565,s:.45});}for(const [i,o]of map.obstacles.entries())scenery.push({type:i<2?'tree':'pillar',...o,s:i<2?.4:.45});RubraWorld.expandGround();
}
tree=function(x,y,s){if(map===C.maps.tutorial||!assetImages.tree)return original.tree(x,y,s);const img=assetImages.tree;ctx.drawImage(img,Math.round(x-img.width*s/2),Math.round(y-img.height*s),Math.round(img.width*s),Math.round(img.height*s));};
pillar=function(x,y){if(map===C.maps.tutorial||!assetImages.shrine)return original.pillar(x,y);const img=assetImages.shrine;ctx.drawImage(img,x-24,y-69,48,69);};
function spriteAt(img,x,y,height,flip=false){const width=height*img.width/img.height;ctx.save();ctx.translate(Math.round(x),Math.round(y+3));if(flip)ctx.scale(-1,1);ctx.drawImage(img,Math.round(-width/2),-Math.round(height),Math.round(width),Math.round(height));ctx.restore();}
drawSprite=function(type,x,y,scale,frame,flip,flash){if(type==='hero'&&characterFrames[run?.character||save.selectedCharacter]){const frames=characterFrames[run?.character||save.selectedCharacter][player.facing||'front'];const f=player.moving?Math.floor(time*C.visuals.walkFps)%frames.length:0;spriteAt(frames[f],x,y,C.visuals.worldHeight);return;}const enemy=enemies.find(e=>e.type===type&&Math.abs(e.x-x)<1&&Math.abs(e.y-y)<8);const cfg=enemy?.cfg;if(cfg?.asset&&assetImages[cfg.asset]){spriteAt(assetImages[cfg.asset],x,y,cfg.size,flip);if(cfg.ring){ctx.strokeStyle=cfg.ring;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y+2,cfg.r,5,0,0,TAU);ctx.stroke();}return;}if(type==='boss'&&map===C.maps.tutorial){original.drawSprite('boss',x,y,3.4,0,flip,flash);ctx.strokeStyle='#9bccad';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-17,y-67);ctx.lineTo(x-31,y-87);ctx.lineTo(x-26,y-92);ctx.moveTo(x+17,y-67);ctx.lineTo(x+31,y-87);ctx.lineTo(x+26,y-92);ctx.stroke();glow(x,y-55,38,'#8ddd9820');return;}original.drawSprite(type,x,y,scale,frame,flip,flash);};
async function loadAssets(){for(const [id,path]of Object.entries(C.assets)){const img=new Image();img.src=path;try{await img.decode();assetImages[id]=img;}catch{console.warn('Asset indisponível: '+path);}}try{const sprites=RubraSprites.build(assetImages);characterFrames={noctis:sprites.noctis,rubra:sprites.rubra};heroFrames=sprites.noctis;portraitFrames=sprites.portraits;}catch(error){$('saveNotice').textContent='Falha ao preparar personagens: '+error.message;console.error(error);return;}assetReady=true;buildGround();$('beginRun').disabled=false;$('startButton').disabled=false;}
// JPEG checkerboard is opaque. Flood only neutral exterior pixels; preserve dark clothing.
// Explicit cell map: row 2 cols 1..5 face right, row 2 col 6 back, row 3 col 1 front.
function makeHeroFrames(img){const cells=[[0,1],[1,1],[2,1],[3,1],[4,1],[5,1],[0,2]],raw=[];for(const [col,row]of cells){const sx=Math.round(col*img.width/6),sy=Math.round(row*img.height/4),w=Math.round((col+1)*img.width/6)-sx,h=img.height/4;const c=document.createElement('canvas');c.width=w;c.height=h;const q=c.getContext('2d',{willReadFrequently:true});q.drawImage(img,sx,sy,w,h,0,0,w,h);const d=q.getImageData(0,0,w,h),seen=new Uint8Array(w*h),queue=[];const neutral=i=>{const p=i*4;return Math.max(d.data[p],d.data[p+1],d.data[p+2])-Math.min(d.data[p],d.data[p+1],d.data[p+2])<35&&d.data[p]>30;};const add=i=>{if(i>=0&&i<w*h&&!seen[i]&&neutral(i)){seen[i]=1;queue.push(i);}};for(let x=0;x<w;x++){add(x);add((h-1)*w+x);}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1);}for(let k=0;k<queue.length;k++){const i=queue[k],x=i%w;d.data[i*4+3]=0;if(x>0)add(i-1);if(x<w-1)add(i+1);add(i-w);add(i+w);}let left=w,right=0,top=h,bottom=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;if(d.data[i+3]){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}}q.putImageData(d,0,0);raw.push({c,left,top,width:right-left+1,height:bottom-top+1});}
 const ratio=48/Math.max(...raw.map(r=>r.height));const frames=raw.map(r=>{const c=document.createElement('canvas');c.width=c.height=64;const q=c.getContext('2d');q.imageSmoothingEnabled=false;const w=Math.round(r.width*ratio),h=Math.round(r.height*ratio);q.drawImage(r.c,r.left,r.top,r.width,r.height,32-Math.round(w/2),60-h,w,h);return c;});heroFrames={right:frames.slice(0,5),left:frames.slice(0,5),back:[frames[5]],front:[frames[6]]};}
function begin(resume=false){if(!assetReady)return;const old=resume?save.active:null;if(resume&&!old)return;if(!old&&(!save.characters.includes(save.selectedCharacter)||!save.maps.includes(save.selectedMap)))return;if(!resume&&save.active){K.settle(save,save.active,'abandon');storeSave();}original.reset();shots=[];effects=[];loot=[];weaponClocks={};projectiles=[];entityId=0;spawnClock=1;checkpointClock=0;eliteIndex=0;const character=old?.character||save.selectedCharacter,mapId=old?.map||save.selectedMap,c=C.characters[character];map=C.maps[mapId];player={...player,...map.spawn,hp:c.hp,maxHp:c.hp,speed:c.speed,r:c.radius,armed:false,damage:c.damage,attackSpeed:c.attackSpeed,range:c.range,facing:'front',dashCooldown:0,invuln:1.5};
 run=old?JSON.parse(JSON.stringify(old)):{id:safeId(),character,map:mapId,elapsed:0,kills:0,gold:0,xp:0,level:1,weapons:[{id:K.startWeapon(character,mapId),level:1}],bossSpawned:false,bossKilled:false};
 if(!old&&profile==='laboratory'&&save.options.testArsenal!==false){run.weapons=[{id:K.startWeapon(character,mapId),level:1},...save.weapons.filter(id=>id!==K.startWeapon(character,mapId)&&K.allowedWeapon(mapId,id)).map(id=>({id,level:1}))].slice(0,C.slots);}
 elapsed=run.elapsed;killCount=run.kills;if(old){player.x=old.player?.x||map.spawn.x;player.y=old.player?.y||map.spawn.y;player.hp=Math.max(1,Math.min(c.hp,finite(old.player?.hp,c.hp)));if(!K.validPoint(player,map,player.r))Object.assign(player,map.spawn);eliteIndex=Math.floor(run.elapsed/(map.eliteEvery||999999));restoreEntities(old);}
 elapsed=run.elapsed;killCount=run.kills;wave=Math.min(5,1+Math.floor(elapsed/(map.bossAt/4)));sword=null;buildGround();hideScreens();state='playing';for(const id of ['hud','runExtra','mobile','dashMeter'])$(id).classList.remove('hidden');$('bossHud').classList.toggle('hidden',!enemies.some(e=>e.type==='boss'));K.unlock(save,run);save.active=run;snapshot();updateHud();initAudio();toast(resume?'Expedição retomada.':'Colete cristais para evoluir e ouro para guardar.',3);if(run.bossKilled){finish(true);return;}if(run.pendingChoice)levelUp(true);}
start=()=>begin(false);
function snapshot(){if(!run||['victory','gameover','end'].includes(state))return;run.elapsed=elapsed;run.kills=killCount;run.player={x:player.x,y:player.y,hp:player.hp};run.entities=enemies.filter(e=>!e.dead).map(e=>({id:e.id,key:e.key,x:e.x,y:e.y,hp:e.hp,maxHp:e.maxHp,type:e.type}));run.loot=eligibleLoot().map(d=>({id:d.id,x:d.x,y:d.y,kind:d.kind,value:d.value}));save.active=JSON.parse(JSON.stringify(run));storeSave();}
function restoreEntities(old){enemies=[];for(const v of (Array.isArray(old.entities)?old.entities:[]).slice(0,C.limits.enemies)){const cfg=v.type==='boss'?map.boss:C.enemies[v.key];if(!cfg||!K.validPoint(v,map,cfg.r))continue;const e=newEnemy(v.key,{x:v.x,y:v.y},v.type==='boss');e.hp=Math.max(1,Math.min(e.maxHp,finite(v.hp,e.maxHp)));enemies.push(e);}loot=[];for(const v of (Array.isArray(old.loot)?old.loot:[]).slice(0,C.limits.drops)){if(['gold','xp','heart'].includes(v.kind)&&K.validPoint(v,map,2))loot.push({...v,id:++entityId,value:K.integer(v.value,1000),life:C.combat.dropLife,collected:false});}if(old.bossSpawned&&!old.bossKilled&&!enemies.some(e=>e.type==='boss'))spawnMapBoss();}
function newEnemy(key,pos,boss=false){const cfg=boss?map.boss:C.enemies[key];const factor=boss?1:1+Math.min(C.combat.hpScaleMax,elapsed/map.bossAt*C.combat.hpScaleRate);return {id:++entityId,key,type:boss?'boss':cfg.sprite||key,cfg,...pos,hp:cfg.hp*factor,maxHp:cfg.hp*factor,r:cfg.r,speed:cfg.speed,flash:0,knockX:0,knockY:0,phase:0,action:cfg.attackInterval||cfg.interval||3,mode:'hunt',dead:false};}
function spawnMapBoss(){if(!run||run.bossKilled||enemies.some(e=>e.type==='boss'))return;const pos=K.spawnPoint(map,player,C.combat.bossSafeDistance,map.boss.r);if(!pos)return;run.bossSpawned=true;enemies.push(newEnemy('boss',pos,true));$('bossHud').classList.remove('hidden');toast(map.boss.name+' · prepare-se!',5);beep(90,.6,'triangle',.06);snapshot();}
function spawnMob(key){if(enemies.length>=C.limits.enemies)return;const cfg=C.enemies[key];const pos=K.spawnPoint(map,player,C.combat.spawnSafeDistance,cfg.r);if(pos)enemies.push(newEnemy(key,pos));}
function moveBody(e,dx,dy){const r=e.r||8;if(K.validPoint({x:e.x+dx,y:e.y},map,r))e.x+=dx;if(K.validPoint({x:e.x,y:e.y+dy},map,r))e.y+=dy;}
function putLoot(kind,value,pos){if(!value)return;let p=K.validPoint(pos,map,3)?pos:K.freePoint(map,null,0,3);if(!p)return;const list=eligibleLoot();if(list.length>=C.limits.drops){const same=list.find(d=>d.kind===kind);if(same){same.value=K.integer(same.value+value);same.life=C.combat.dropLife;}return;}loot.push({id:++entityId,x:p.x,y:p.y,kind,value,life:C.combat.dropLife,collected:false});}
function reward(e){killCount++;run.kills=killCount;if(e.type==='boss'){if(run.bossKilled)return;run.bossKilled=true;run.gold=K.integer(run.gold+e.cfg.gold);K.unlock(save,run);snapshot();finish(true);return;}putLoot('xp',e.cfg.xp,e);if(Math.random()<e.cfg.goldChance)putLoot('gold',e.cfg.gold,{x:e.x+9,y:e.y});if(Math.random()<C.combat.healChance)putLoot('heart',1,{x:e.x-9,y:e.y});}
function damageEnemy(e,amount){if(!K.hit(e,amount,reward))return;e.flash=.12;if(save.options.particles&&particles.length<C.limits.particles-6)burst(e.x,e.y-10,'#eac790',5);if(texts.length<35)floating(Math.round(amount),e.x,e.y-26);}
damagePlayer=function(amount=1){if(state!=='playing'||player.invuln>0||player.dash>0)return;player.hp=Math.max(0,player.hp-amount);player.invuln=C.contactCooldown;shake=5;beep(130,.12,'sawtooth',.04);if(!player.hp)finish(false);};
dash=function(){if(state!=='playing'||player.dashCooldown>0)return;original.dash();player.dashCooldown=C.characters[run.character].dashCooldown;};
function nearest(from,range){let target=null,best=range;for(const e of alive()){const d=dist(e,from);if(d<best){best=d;target=e;}}return target;}
function effect(e){if(effects.length<C.limits.effects)effects.push(e);}
function fire(slot){const w=K.stats(slot,player),target=nearest(player,w.range);if(w.kind==='orbital'){effect({kind:'orbit',x:player.x,y:player.y,r:w.range,color:w.color,life:.28,max:.28,count:w.count,id:slot.id});for(const e of alive())if(dist(player,e)<=w.range+e.r)damageEnemy(e,w.damage);return;}if(!target)return;if(w.kind==='area'){effect({kind:'area',x:target.x,y:target.y,r:w.radius,color:w.color,life:.55,max:.55,delay:.3,damage:w.damage,hit:false});return;}const a=Math.atan2(target.y-player.y,target.x-player.x);for(let i=0;i<w.count&&shots.length<C.limits.projectiles;i++){const angle=a+(i-(w.count-1)/2)*.13;shots.push({id:++entityId,x:player.x,y:player.y-8,vx:Math.cos(angle)*w.speed,vy:Math.sin(angle)*w.speed,life:w.range/w.speed,damage:w.damage,color:w.color,weapon:slot.id,kind:w.kind,pierce:w.pierce||1,hit:new Set(),hostile:false});}}
function enemyAttack(e){if(e.type==='boss'){e.phase++;const stage=e.hp/e.maxHp<C.combat.phaseThreshold;const target={x:player.x,y:player.y};if(e.phase%2){e.telegraph={kind:'ring',x:e.x,y:e.y,time:C.combat.ringWindup,count:stage?C.combat.enragedRingCount:C.combat.ringCount};}else{e.telegraph={kind:'charge',x:e.x,y:e.y,tx:target.x,ty:target.y,time:stage?C.combat.enragedWindup:C.combat.chargeWindup};}e.action=e.cfg.interval*(stage?C.combat.phaseInterval:1);}else{e.telegraph={kind:'shot',x:e.x,y:e.y,tx:player.x,ty:player.y,time:C.combat.shotWindup};e.action=e.cfg.attackInterval;}}
function releaseAttack(e,t){const add=(a,speed)=>{if(shots.length<C.limits.projectiles)shots.push({id:++entityId,x:e.x,y:e.y-8,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:C.combat.projectileLife,damage:e.cfg.damage,color:e.type==='boss'?'#f487ad':'#8fb8ff',hostile:true,hit:new Set(),pierce:1});};if(t.kind==='ring'){for(let i=0;i<t.count;i++)add(i*TAU/t.count+e.phase*.37,C.combat.bossProjectileSpeed); }else if(t.kind==='charge'){e.charge={angle:Math.atan2(t.ty-e.y,t.tx-e.x),time:C.combat.chargeSeconds};}else add(Math.atan2(t.ty-e.y,t.tx-e.x),C.combat.mobProjectileSpeed);}
function collect(d){if(d.collected||!run)return;d.collected=true;if(d.kind==='gold')run.gold=K.integer(run.gold+d.value);if(d.kind==='xp')run.xp=K.integer(run.xp+d.value);if(d.kind==='heart')player.hp=Math.min(player.maxHp,player.hp+d.value);}
function needsLevel(){return run&&run.xp>=C.xp.base+(run.level-1)*C.xp.perLevel;}
function levelUp(resuming=false){if(!resuming){run.xp-=C.xp.base+(run.level-1)*C.xp.perLevel;run.level++;}run.pendingChoice=true;offered=K.choices(run,save);screen('upgrade');$('upgradeTitle').textContent='Nível '+run.level+' · escolha seu poder';$('levelChoices').replaceChildren();for(const choice of offered){const b=document.createElement('button');b.className='choice';const w=C.weapons[choice.id];b.innerHTML=w?`<span style="color:${w.color}">${RubraWeaponArt.iconHtml(choice.id)}</span><strong>${w.name} · Nv. ${choice.level}</strong><small>${w.description}<br>${choice.level===1?'Nova arma':'Melhoria de arma equipada'}</small>`:`<span>${choice.kind==='heal'?'♥':'✦'}</span><strong>${choice.kind==='heal'?'Recuperar 2 corações':'+'+C.economy.fallbackGold+' ouro'}</strong><small>Recompensa alternativa</small>`;b.onclick=()=>chooseLevel(choice);$('levelChoices').append(b);}snapshot();}
function chooseLevel(choice){if(state!=='upgrade'||!offered.includes(choice))return;if(K.upgrade(run,save,choice)){if(choice.kind==='heal')player.hp=Math.min(player.maxHp,player.hp+C.economy.fallbackHeal);for(const s of run.weapons)weaponClocks[s.id]=.2;offered=[];run.pendingChoice=false;hideScreens();state='playing';snapshot();updateHud();}}
update=function(dt){time+=dt;if(state!=='playing'||!run)return;elapsed+=dt;run.elapsed=elapsed;toastTime-=dt;if(toastTime<=0)$('toast').classList.add('hidden');player.invuln=Math.max(0,player.invuln-dt);player.dashCooldown=Math.max(0,player.dashCooldown-dt);shake=Math.max(0,shake-dt*24);let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.y;const len=Math.hypot(dx,dy);player.moving=len>.1;if(len>.1){dx/=Math.max(1,len);dy/=Math.max(1,len);player.facing=Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'back':'front';player.flip=dx<0;dashDirection={x:dx/Math.hypot(dx,dy),y:dy/Math.hypot(dx,dy)};}if(player.dash>0){player.dash=Math.max(0,player.dash-dt);dx=dashDirection.x*3.8;dy=dashDirection.y*3.8;}moveBody(player,dx*player.speed*dt,dy*player.speed*dt);
 spawnClock-=dt;if(spawnClock<=0&&!run.bossKilled){const pool=map.enemies.slice(0,Math.min(map.enemies.length,2+Math.floor(elapsed/C.combat.enemyTierSeconds)));spawnMob(pool[Math.floor(Math.random()*pool.length)]);spawnClock=Math.max(map.minInterval,map.spawnInterval-elapsed/map.bossAt*C.combat.spawnAcceleration)*(run.bossSpawned?C.combat.bossSpawnMultiplier:1);}
 if(map.eliteEvery&&Math.floor(elapsed/map.eliteEvery)>eliteIndex){eliteIndex++;spawnMob('elite');}if(elapsed>=map.bossAt&&!run.bossSpawned)spawnMapBoss();const newly=K.unlock(save,run);if(newly.length){toast('Arma desbloqueada: '+newly.map(id=>C.weapons[id].name).join(', '),4);snapshot();}
 for(const e of enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);const d=Math.max(1,dist(e,player)),speed=e.cfg.speed;if(e.telegraph){e.telegraph.time-=dt;if(e.telegraph.time<=0){releaseAttack(e,e.telegraph);e.telegraph=null;}}else if(e.charge){moveBody(e,Math.cos(e.charge.angle)*C.combat.chargeSpeed*dt,Math.sin(e.charge.angle)*C.combat.chargeSpeed*dt);e.charge.time-=dt;if(e.charge.time<=0)e.charge=null;}else{const factor=e.cfg.behavior==='ranged'?(d<C.combat.rangedNear?-C.combat.rangedRetreat:d>C.combat.rangedFar?1:0):1;moveBody(e,(player.x-e.x)/d*speed*factor*dt,(player.y-e.y)/d*speed*factor*dt);if(e.type==='boss'||e.cfg.behavior==='ranged'){e.action-=dt;if(e.action<=0)enemyAttack(e);}}if(dist(e,player)<e.r+player.r)damagePlayer(e.cfg.damage);if(state!=='playing')return;}
 for(const slot of run.weapons){weaponClocks[slot.id]=(weaponClocks[slot.id]??.1)-dt;if(weaponClocks[slot.id]<=0){fire(slot);weaponClocks[slot.id]=K.stats(slot,player).interval;}if(state!=='playing')return;}
 for(const s of shots){s.life-=dt;const oldX=s.x,oldY=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;if(!K.validPoint(s,map,2)){s.life=0;continue;}if(s.hostile){if(dist(s,player)<player.r+5){damagePlayer(s.damage);s.life=0;}}else{for(const e of alive()){if(s.hit.has(e.id))continue;const vx=s.x-oldX,vy=s.y-oldY,l=vx*vx+vy*vy,t=l?clamp(((e.x-oldX)*vx+(e.y-oldY)*vy)/l,0,1):0;if(Math.hypot(e.x-oldX-vx*t,e.y-oldY-vy*t)<e.r+4){s.hit.add(e.id);damageEnemy(e,s.damage);if(--s.pierce<=0){s.life=0;break;}}}}if(state!=='playing')return;}
 shots=shots.filter(s=>s.life>0);for(const ef of effects){ef.life-=dt;if(ef.kind==='area'&&!ef.hit&&ef.life<=ef.max-ef.delay){ef.hit=true;for(const e of alive())if(dist(e,ef)<ef.r+e.r)damageEnemy(e,ef.damage);if(state!=='playing')return;}}effects=effects.filter(e=>e.life>0);enemies=enemies.filter(e=>!e.dead&&(!map.world||e.type==='boss'||dist(e,player)<map.world.despawnDistance));
 for(const d of loot){if(d.collected)continue;d.life-=dt;if(dist(d,player)<C.pickupRadius&&(d.kind!=='heart'||player.hp<player.maxHp))collect(d);}loot=loot.filter(d=>!d.collected&&d.life>0);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}particles=particles.filter(p=>p.life>0).slice(-C.limits.particles);for(const t of texts){t.life-=dt;t.y-=dt*25;}texts=texts.filter(t=>t.life>0);checkpointClock+=dt;if(checkpointClock>=C.checkpointSeconds){checkpointClock=0;snapshot();}updateHud();if(needsLevel())levelUp();};
updateHud=function(){if(!run)return;$('hearts').textContent='♥'.repeat(Math.max(0,player.hp))+'♡'.repeat(Math.max(0,player.maxHp-player.hp));$('waveLabel').textContent=map.subtitle;$('waveInfo').textContent=run.bossSpawned?'Derrote o guardião':'Guardião em '+formatTime(Math.max(0,map.bossAt-elapsed));$('kills').textContent=killCount;$('timer').textContent=formatTime(elapsed);$('dashFill').style.width=100*(1-player.dashCooldown/C.characters[run.character].dashCooldown)+'%';$('runGold').textContent=run.gold;$('levelLabel').textContent='NÍVEL '+run.level;$('xpFill').style.width=Math.min(100,run.xp/(C.xp.base+(run.level-1)*C.xp.perLevel)*100)+'%';const slots=run.weapons.map(s=>`${s.id}:${s.level}`).join(',');if($('weaponSlots').dataset.value!==slots){$('weaponSlots').dataset.value=slots;$('weaponSlots').innerHTML=run.weapons.map(s=>`<div class="weapon-slot" title="${C.weapons[s.id].name}" style="color:${C.weapons[s.id].color}">${RubraWeaponArt.iconHtml(s.id)}<small>NV ${s.level}</small></div>`).join('')+Array(Math.max(0,C.slots-run.weapons.length)).fill('<div class="weapon-slot" style="opacity:.3">＋</div>').join('');}const boss=enemies.find(e=>e.type==='boss'&&!e.dead);if(boss){$('bossHud').querySelector('.boss-title').textContent=map.boss.name+(boss.hp<boss.maxHp*.5?' · ENFURECIDO':'');$('bossFill').style.width=boss.hp/boss.maxHp*100+'%';}for(const [i,el]of [...$('waveTrack').children].entries())el.classList.toggle('done',elapsed/map.bossAt>=i/5);};
render=function(){const camera=RubraWorld.camera(map,player);ctx.save();ctx.translate(-camera.x,-camera.y);if(map.world)RubraWorld.renderBase(camera);else original.render();if(save.options.particles===false){/* Combat telegraphs remain visible; decorative legacy spores are capped at 25. */}for(const d of loot){if(d.collected)continue;ctx.fillStyle=d.kind==='gold'?'#f2cb73':d.kind==='xp'?'#85d9df':'#ef8192';if(d.kind==='heart'){ctx.font='13px monospace';ctx.fillText('♥',d.x,d.y);}else{ctx.save();ctx.translate(Math.round(d.x),Math.round(d.y));ctx.rotate(Math.PI/4);ctx.fillRect(-3,-3,6,6);ctx.restore();}}for(const e of enemies){const t=e.telegraph;if(!t)continue;ctx.strokeStyle=t.kind==='shot'?'#adc8ff':'#ffa3a3';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();if(t.kind==='ring')ctx.arc(e.x,e.y,40+(1-t.time)*18,0,TAU);else{ctx.moveTo(e.x,e.y);ctx.lineTo(t.tx,t.ty);}ctx.stroke();ctx.setLineDash([]);if(t.kind==='charge'){ctx.fillStyle='#ef78841a';ctx.beginPath();ctx.arc(t.tx,t.ty,22,0,TAU);ctx.fill();}}
 if(run&&['playing','paused','upgrade','help'].includes(state)){for(const slot of run.weapons){const w=K.stats(slot,player);if(w.kind!=='orbital')continue;RubraWeaponArt.orbit(ctx,slot,player,time,w);}}
 for(const s of shots)RubraWeaponArt.shot(ctx,s);for(const e of effects)RubraWeaponArt.effect(ctx,e,time);

 ctx.restore();
 if(state==='characters')for(const el of document.querySelectorAll('[data-portrait]')){const q=el.getContext('2d');q.imageSmoothingEnabled=false;q.clearRect(0,0,64,64);const frames=characterFrames[el.dataset.portrait]?.front;if(el.dataset.portrait==='noctis'&&portraitFrames.noctis){const bob=save.options.particles?Math.round(Math.sin(time*2.4)):0;q.drawImage(portraitFrames.noctis,0,bob);if(save.options.particles){q.fillStyle='#ad547f';for(let i=0;i<3;i++){const a=time*1.4+i*TAU/3,x=Math.round(32+Math.cos(a)*25),y=Math.round(31+Math.sin(a)*15);q.fillRect(x-2,y,5,1);q.fillRect(x-3,y-1,2,1);q.fillRect(x+2,y-1,2,1);}}}else if(frames)q.drawImage(frames[Math.floor(time*C.visuals.walkFps)%frames.length],0,0);}

};
finish=function(win,outcome){if(!run||save.lastResult?.id===run.id)return;run.elapsed=elapsed;run.kills=killCount;K.unlock(save,run);save.active=run;if(!K.settle(save,run,outcome||(win?'victory':'death')))return;storeSave();screen(win?'end':'end');state=win?'victory':'gameover';$('endTitle').textContent=win?'O GUARDIÃO CAIU.':outcome==='abandon'?'EXPEDIÇÃO ENCERRADA':'A NOITE CONTINUA.';$('endEyebrow').textContent=map.name;$('endText').textContent=`${killCount} inimigos · ${formatTime(elapsed)} · Ouro guardado: ${run.gold} · Saldo: ${save.gold}. ${win?(run.map==='tutorial'?'Tutorial concluído! Noctis e Necrópole desbloqueados.':'Expedição concluída! Lança do túmulo desbloqueada.'):''}`;for(const id of ['mobile','bossHud','toast'])$(id).classList.add('hidden');wallet();};
togglePause=function(){if(state==='playing'){snapshot();screen('pause');state='paused';}else if(state==='paused'){hideScreens();state='playing';}};
$('startButton').onclick=charactersScreen;$('continueRun').onclick=()=>begin(true);$('charactersBack').onclick=menu;$('charactersNext').onclick=mapsScreen;$('mapsBack').onclick=charactersScreen;$('beginRun').onclick=()=>begin(false);$('retryButton').onclick=()=>begin(false);$('endMenuButton').onclick=menu;$('resumeButton').onclick=togglePause;$('pauseButton').onclick=togglePause;$('quitButton').onclick=()=>finish(false,'abandon');$('saveQuit').onclick=()=>{snapshot();if(!saveError)menu();};
function optionsScreen(){menuReturn=state;$('soundOption').checked=save.options.sound;$('particlesOption').checked=save.options.particles;screen('options');}
$('optionsButton').onclick=optionsScreen;$('closeOptions').onclick=()=>screen(menuReturn);$('soundOption').onchange=()=>{save.options.sound=$('soundOption').checked;soundOn=save.options.sound;$('soundButton').textContent=soundOn?'♫ Som: on':'♫ Som: off';storeSave();initAudio();};$('particlesOption').onchange=()=>{save.options.particles=$('particlesOption').checked;storeSave();wallet();};
$('soundButton').onclick=()=>{soundOn=!soundOn;save.options.sound=soundOn;$('soundButton').textContent=soundOn?'♫ Som: on':'♫ Som: off';storeSave();initAudio();};
$('helpTop').onclick=()=>{if(state==='help')return;previousState=state;clearInput();state='help';$('help').classList.remove('hidden');$('closeHelp').focus();};$('menuControls').onclick=()=>$('helpTop').click();$('closeHelp').onclick=()=>{state=previousState;$('help').classList.add('hidden');clearInput();};
window.addEventListener('keydown',e=>{if(state==='playing')return;if(e.key==='Escape'){if(state==='characters')menu();else if(state==='maps')charactersScreen();else if(state==='options')$('closeOptions').click();}if(['Tab','ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){const panel=[...document.querySelectorAll('.overlay')].reverse().find(el=>!el.classList.contains('hidden'));if(!panel)return;const buttons=[...panel.querySelectorAll('button:not(:disabled),input:not(:disabled)')].filter(b=>!b.classList.contains('hidden'));let i=buttons.indexOf(document.activeElement);i=(i+(['ArrowUp','ArrowLeft'].includes(e.key)||(e.key==='Tab'&&e.shiftKey)?-1:1)+buttons.length)%buttons.length;buttons[i]?.focus();e.preventDefault();}});
window.addEventListener('pagehide',()=>{if(run&&['playing','paused','upgrade','help'].includes(state))snapshot();});
soundOn=save.options.sound;$('soundButton').textContent=soundOn?'♫ Som: on':'♫ Som: off';$('beginRun').disabled=true;$('startButton').disabled=true;menu();loadAssets();
