
'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const W=960,H=540,TAU=Math.PI*2,keys=new Set();let state='menu',previousState='menu',time=0,last=0,elapsed=0,wave=1,waveTime=0,spawnTime=0,spawned=0,killCount=0,player,enemies=[],particles=[],drops=[],texts=[],projectiles=[],afterimages=[],sword,angle=0,turn=0,toastTime=0,shake=0,audioCtx=null,soundOn=false,best=0,joystick={x:0,y:0},dashDirection={x:1,y:0};
try{best=+localStorage.getItem('rubra-best')||0}catch(e){} $('record').textContent=String(best).padStart(3,'0');
const configs=[null,{count:18,interval:1.05,hp:24,speed:33,name:'O despertar'},{count:29,interval:.76,hp:34,speed:39,name:'Asas na escuridão'},{count:40,interval:.59,hp:47,speed:45,name:'O cerco das sombras'},{count:52,interval:.43,hp:60,speed:49,name:'A última horda'}];
let seed=4816;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function rect(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),w,h)}
const palettes={hero:{o:'#172132',r:'#a52e49',R:'#ec5967',h:'#743945',H:'#c55554',s:'#f2c29a',S:'#be836f',e:'#243c4c',g:'#e9c589',b:'#5d3842',B:'#97605a',w:'#c7b4a1'},vamp:{o:'#131629',r:'#542b59',R:'#98395c',s:'#b9bad3',e:'#ff6d8a',h:'#34314c',g:'#ead3bc',b:'#35253f'},shade:{o:'#142130',r:'#253c59',R:'#3e607c',s:'#6eacb5',e:'#a0f7e4',h:'#294255',g:'#a3d4c6',b:'#21374d'},bat:{o:'#15182b',r:'#453459',R:'#70517c',s:'#866993',e:'#ff8b9a',h:'#342c47',g:'#edb5b6',b:'#2c2640'},boss:{o:'#181326',r:'#442541',R:'#a1405a',s:'#b8a9ba',e:'#ffbdad',h:'#443043',g:'#e3bd82',b:'#261c34'}};
const sprites={hero:['......rrr.......','....rrRRRrr.....','...rrRRRRRrr....','..rrRRRRRRRrr...','..rrHHHHHHrrr...','...HHHHHHHH.....','..gssessessg....','...sssssss......','....SsssS.......','...rRRgRRr......','..rRRRgRRRr.....','.srRRRgRRRrs....','.ssrRRRRRrss....','...rrgggrr......','...rRRRRRr......','....bb.bb.......','....bb.bb.......','...BBB.BBB......'],vamp:['....hhhhhh......','...hhoooohh.....','...hssssssh.....','...sesseses.....','....sgssgs......','.....ssss.......','..r..RRRR..r....','.rRrrRsRrrRRr...','rRRRrRRRRrRRRr..','rRRRrrRRrrRRRr..','.rRRRrrrrRRRr...','..rRRRrrRRRr....','...rRrrrrRr.....','....bb..bb......','...bbb..bbb.....'],shade:['.....oo.........','....oRro........','...oRRRro.......','..oRRRRRro......','..orRRRRro......','.orRooooRro.....','.orReooeRro.....','..orooooRro.....','..orRRRRro......','.orRRRRRRro.....','.orRRrRRRro.....','orRRrrrRRRro....','orRrr.rrRRro....','.orrr..rrro.....','..or....ro......'],bat:['o............o..','oro........oro..','oRro......orRo..','oRRro.oo.orRRo..','oRRRroRRoRRRRo..','orRRRReeRRRRro..','.orRRRRRRRRro...','..orrRRRRrro....','...ooRssRoo.....','.....oooo.......'],boss:['...g........g...','...gg......gg...','...gRggggggRg...','....gRRRRRRg....','....hhhhhhhh....','...hssssssssh...','...hseesseesh...','....ssssssss....','.....sgssgs.....','..rrrRssssRrrr..','.rRRRRRggRRRRRr.','rRRRRRRggRRRRRRr','rRRRrRRRRRRrRRRr','rRRrrRRggRRrrRRr','rRrrrRRRRRRrrrRr','rRrrrRggggRrrrRr','rrr.rRRRRRRr.rrr','rr..rRRRRRRr..rr','r...rrRRRRrr...r','....bbb..bbb....','...bbbb..bbbb...']};
const spriteCache={};function spriteImage(type,frame=0){const key=type+frame;if(spriteCache[key])return spriteCache[key];const rows=sprites[type],c=document.createElement('canvas');c.width=16;c.height=rows.length;const g=c.getContext('2d');rows.forEach((row,y)=>[...row].forEach((v,x)=>{if(v!=='.'){let xx=x,yy=y;if(frame&&y>rows.length-4){yy+=x<8?1:-1}if(type==='bat'&&frame&&(x<5||x>10))yy+=2;rect(g,xx,yy,1,1,palettes[type][v]||'#fff')}}));return spriteCache[key]=c}
function drawSprite(type,x,y,scale=2,frame=0,flip=false,flash=false){const img=spriteImage(type,frame);ctx.save();ctx.translate(Math.round(x),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(img,-8*scale,-(img.height-3)*scale,16*scale,img.height*scale);if(flash){ctx.globalCompositeOperation='source-atop';}ctx.restore()}
const ground=document.createElement('canvas');ground.width=W;ground.height=H;const g=ground.getContext('2d');
function makeGround(){rect(g,0,0,W,H,'#203538');for(let y=0;y<H;y+=24)for(let x=0;x<W;x+=24){const colors=['#22383a','#243a3b','#263c3c','#21373a','#283d3c'];rect(g,x,y,24,24,colors[Math.floor(rand()*colors.length)]);for(let n=0;n<9;n++){const px=x+Math.floor(rand()*11)*2,py=y+Math.floor(rand()*11)*2;rect(g,px,py,rand()<.3?4:2,2,rand()<.5?'#304846':'#1d3236')}}
// Broken flagstones form an ancient courtyard, with moss growing through each seam.
for(let y=65;y<480;y+=30)for(let x=90;x<875;x+=40){if(rand()>.73)continue;const px=x+((Math.floor(y/30)%2)*18),py=y+Math.floor(rand()*3)*2;rect(g,px+2,py+2,34,24,'#182f34');rect(g,px,py,34,22,['#334747','#354a49','#304547','#3c4d4c'][Math.floor(rand()*4)]);rect(g,px+2,py,28,2,'#49605a');rect(g,px+2,py+20,32,2,'#263c40');if(rand()<.6){rect(g,px+8,py+4,2,6,'#2b4142');rect(g,px+10,py+8,6,2,'#2b4142')}for(let n=0;n<3;n++)rect(g,px+Math.floor(rand()*14)*2,py+Math.floor(rand()*10)*2,4,2,'#3c5550')}
for(let i=0;i<1400;i++){const x=Math.floor(rand()*W/2)*2,y=Math.floor(rand()*H/2)*2;if(rand()<.5){rect(g,x,y,2,4,'#38594a');rect(g,x+2,y-2,2,4,'#41634f')}else rect(g,x,y,2,2,'#607359')}
for(let i=0;i<80;i++){const x=rand()*W,y=rand()*H;rect(g,x,y,4,2,'#817790');if(rand()<.4)rect(g,x+2,y-2,2,2,'#bda4b8')}
// A central engraved summoning circle.
g.strokeStyle='#61716b';g.lineWidth=2;g.globalAlpha=.35;g.beginPath();g.ellipse(500,287,106,58,0,0,TAU);g.stroke();g.beginPath();g.ellipse(500,287,97,52,0,0,TAU);g.stroke();for(let i=0;i<12;i++){let a=i*TAU/12;rect(g,500+Math.cos(a)*102,287+Math.sin(a)*55,4,4,'#a2a084')}g.globalAlpha=1;
}makeGround();
const scenery=[];for(let x=5;x<W;x+=47){scenery.push({type:'tree',x:x+rand()*15,y:28+rand()*16,s:1+rand()*.3});scenery.push({type:'tree',x:x+rand()*18,y:H+25+rand()*20,s:1+rand()*.3})}for(let y=83;y<H-15;y+=70){scenery.push({type:'tree',x:14+rand()*9,y,s:1.15});scenery.push({type:'tree',x:W-15-rand()*8,y,s:1.15})}for(const p of [[134,142],[808,142],[130,428],[820,428]])scenery.push({type:'pillar',x:p[0],y:p[1]});
function tree(x,y,s){ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.scale(s,s);ctx.fillStyle='#0b202ab0';ctx.beginPath();ctx.ellipse(0,5,27,10,0,0,TAU);ctx.fill();rect(ctx,-5,-33,10,38,'#243036');rect(ctx,-3,-25,3,26,'#475047');const layers=[[-31,-42,62,20,'#102933'],[-27,-55,54,24,'#15343a'],[-23,-68,46,26,'#1d4141'],[-16,-79,32,28,'#285148'],[-9,-87,18,24,'#315d4d']];for(const [xx,yy,w,h,c]of layers){rect(ctx,xx,yy,w,h,c);rect(ctx,xx-4,yy+8,w+8,h-14,c)}for(let i=0;i<12;i++){let xx=((i*17)%42)-21,yy=-37-((i*13)%39);rect(ctx,xx,yy,6,2,i%3?'#315949':'#427057')}ctx.restore()}
function pillar(x,y){rect(ctx,x-15,y,36,8,'#152831');rect(ctx,x-14,y-9,28,12,'#465354');rect(ctx,x-9,y-46,18,39,'#536061');rect(ctx,x-7,y-44,4,32,'#69746e');rect(ctx,x+5,y-42,4,33,'#303f49');rect(ctx,x-13,y-49,26,8,'#68736c');rect(ctx,x-10,y-52,20,4,'#87907b');rect(ctx,x-4,y-34,8,12,'#253b43');rect(ctx,x-2,y-32,4,8,'#6bb7a9');rect(ctx,x-14,y-7,8,4,'#506b50')}
function glow(x,y,r,color){const gradient=ctx.createRadialGradient(x,y,0,x,y,r);gradient.addColorStop(0,color);gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.fillRect(x-r,y-r,r*2,r*2)}
function shadow(x,y,r=13){ctx.fillStyle='#07172577';ctx.beginPath();ctx.ellipse(x,y+3,r,r*.38,0,0,TAU);ctx.fill()}
function blade(x,y,a,scale=1){ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.rotate(a);rect(ctx,-2*scale,-28*scale,4*scale,25*scale,'#d9f3ea');rect(ctx,-2*scale,-25*scale,2*scale,22*scale,'#8ebbbd');rect(ctx,0,-29*scale,2*scale,3*scale,'#fff7d9');rect(ctx,-7*scale,-5*scale,14*scale,3*scale,'#e3b668');rect(ctx,-2*scale,-2*scale,4*scale,9*scale,'#93524c');rect(ctx,-3*scale,5*scale,6*scale,3*scale,'#e3b668');ctx.restore()}
function reset(){player={x:408,y:302,hp:5,maxHp:5,speed:151,damage:28,reach:57,attackRate:1.5,invuln:0,dash:0,dashCooldown:0,armed:false,flip:false,moving:false};enemies=[];particles=[];drops=[];texts=[];projectiles=[];afterimages=[];sword={x:512,y:282};angle=0;turn=0;elapsed=0;wave=1;waveTime=0;spawnTime=1.8;spawned=0;killCount=0;shake=0;joystick={x:0,y:0};keys.clear();}
function overlaysOff(){for(const id of ['menu','upgrade','pause','end','help'])$(id).classList.add('hidden')}
function start(){reset();overlaysOff();state='playing';$('hud').classList.remove('hidden');$('mobile').classList.remove('hidden');$('dashMeter').classList.remove('hidden');$('bossHud').classList.add('hidden');toast('Encontre a espada dourada para começar a atacar.',5);initAudio();updateHud();canvas.focus()}
function showMenu(){overlaysOff();state='menu';$('menu').classList.remove('hidden');for(const id of ['hud','mobile','dashMeter','bossHud','toast'])$(id).classList.add('hidden');reset()}
function toast(message,duration=3){$('toast').textContent=message;$('toast').classList.remove('hidden');toastTime=duration}
function initAudio(){if(!audioCtx&&soundOn)try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume()}
function beep(freq,duration=.1,type='sine',vol=.035,slide=0){if(!soundOn||!audioCtx)return;const o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),audioCtx.currentTime+duration);gain.gain.setValueAtTime(vol,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-75,75),vy:rnd(-90,45),life:rnd(.2,.65),max:.65,color,size:Math.random()<.3?4:2})}
function floating(text,x,y,color='#f3d5a0'){texts.push({text,x,y,life:.8,color})}
function pickup(){player.armed=true;sword=null;burst(player.x,player.y-13,'#f2ce88',32);toast('Lâmina desperta! Os cortes agora são automáticos.',3.5);beep(523,.16,'triangle',.08);setTimeout(()=>beep(784,.25,'triangle',.06),100)}
function spawnEnemy(){const c=configs[wave];let x,y;const edge=Math.floor(Math.random()*4);if(edge===0){x=rnd(55,W-55);y=52}else if(edge===1){x=W-47;y=rnd(65,H-40)}else if(edge===2){x=rnd(55,W-55);y=H-30}else{x=45;y=rnd(65,H-40)}if(Math.hypot(x-player.x,y-player.y)<150){x=player.x<W/2?W-50:50;y=player.y<H/2?H-40:55}let type=wave===1?(Math.random()<.7?'vamp':'shade'):['vamp','shade','bat'][Math.floor(Math.random()*3)];const hp=c.hp*(type==='bat'?.62:type==='shade'?1.2:1);enemies.push({x,y,type,hp,maxHp:hp,speed:c.speed*(type==='bat'?1.5:type==='shade'?.82:1),r:type==='bat'?11:13,lastHit:-1,flash:0,knockX:0,knockY:0,phase:rnd(0,TAU)});spawned++}
function spawnBoss(){enemies=[];projectiles=[];enemies.push({x:W/2,y:135,type:'boss',hp:1900,maxHp:1900,speed:42,r:29,lastHit:-1,flash:0,knockX:0,knockY:0,phase:0,action:2.4,mode:'hunt',charge:0,targetX:0,targetY:0});$('bossHud').classList.remove('hidden');toast('Vhalkar chegou. Esquive dos disparos e da investida!',4);beep(95,.8,'sawtooth',.065,-45)}
function nextWave(){wave++;waveTime=0;spawned=0;spawnTime=1.3;state='playing';$('upgrade').classList.add('hidden');if(wave===5)spawnBoss();else toast('Onda '+wave+' — '+configs[wave].name,2.5);updateHud()}
function completeWave(){if(wave===5){finish(true);return}state='upgrade';player.hp=Math.min(player.maxHp,player.hp+1);player.invuln=1.5;drops=[];projectiles=[];$('toast').classList.add('hidden');$('upgradeTitle').textContent='Onda '+wave+' concluída.';$('upgrade').classList.remove('hidden');beep(660,.35,'triangle',.06);updateHud()}
function finish(win){state=win?'victory':'gameover';overlaysOff();$('end').classList.remove('hidden');$('mobile').classList.add('hidden');$('toast').classList.add('hidden');$('endEyebrow').textContent=win?'O amanhecer é seu':'A floresta se lembra';$('endTitle').textContent=win?'A NOITE FOI VENCIDA.':'GAME OVER';$('endText').textContent=(win?'Vhalkar caiu. O bosque volta a respirar. ':'Sua lâmina descansou, mas a noite continua. ')+killCount+' inimigos eliminados · '+formatTime(elapsed)+' · Onda '+wave+'/5.';$('retryButton').innerHTML=win?'Jogar novamente <span>↻</span>':'Tentar novamente <span>↻</span>';if(killCount>best){best=killCount;try{localStorage.setItem('rubra-best',best)}catch(e){}$('record').textContent=String(best).padStart(3,'0')}beep(win?880:140,.65,'triangle',.06,win?220:-100)}
function damagePlayer(){if(player.invuln>0||player.dash>0||state!=='playing')return;player.hp--;player.invuln=1.05;shake=7;burst(player.x,player.y-10,'#f07887',14);beep(130,.17,'sawtooth',.06,-60);updateHud();if(player.hp<=0)finish(false)}
function dash(){if(state!=='playing'||player.dashCooldown>0)return;let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.y;const len=Math.hypot(dx,dy);if(len>.1)dashDirection={x:dx/len,y:dy/len};player.dash=.18;player.dashCooldown=2.5;beep(330,.13,'triangle',.04,500)}
function togglePause(){if(state==='playing'){state='paused';keys.clear();joystick={x:0,y:0};$('stick').style.transform='';$('pause').classList.remove('hidden')}else if(state==='paused'){state='playing';$('pause').classList.add('hidden')}}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}
function updateHud(){$('hearts').innerHTML='♥'.repeat(Math.max(0,player.hp))+'<span class="empty">'+'♥'.repeat(Math.max(0,player.maxHp-player.hp))+'</span>';$('waveLabel').textContent='ONDA 0'+wave+' / 05';$('waveInfo').textContent=wave===5?'O senhor da noite':configs[wave].name;$('kills').textContent=String(killCount).padStart(3,'0');$('timer').textContent=formatTime(elapsed);[...$('waveTrack').children].forEach((el,i)=>el.classList.toggle('done',i<wave));$('dashFill').style.width=(100*(1-player.dashCooldown/2.5))+'%';const boss=enemies.find(e=>e.type==='boss');if(boss)$('bossFill').style.width=Math.max(0,100*boss.hp/boss.maxHp)+'%'}
function update(dt){time+=dt;if(state!=='playing')return;elapsed+=dt;waveTime+=dt;toastTime-=dt;if(toastTime<=0)$('toast').classList.add('hidden');player.invuln=Math.max(0,player.invuln-dt);player.dashCooldown=Math.max(0,player.dashCooldown-dt);shake=Math.max(0,shake-dt*24);
let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.x,dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.y,len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}player.moving=len>.1;if(len>.1){dashDirection={x:dx/Math.hypot(dx,dy),y:dy/Math.hypot(dx,dy)};if(Math.abs(dx)>.1)player.flip=dx<0}if(player.dash>0){player.dash-=dt;dx=dashDirection.x*3.8;dy=dashDirection.y*3.8;afterimages.push({x:player.x,y:player.y,life:.18})}player.x=clamp(player.x+dx*player.speed*dt,43,W-43);player.y=clamp(player.y+dy*player.speed*dt,70,H-30);
if(sword&&dist(player,sword)<29)pickup();
if(wave<5){spawnTime-=dt;if(spawnTime<=0&&spawned<configs[wave].count){spawnEnemy();spawnTime=configs[wave].interval}}
if(player.armed){const previousAngle=angle;angle+=dt*TAU*player.attackRate;turn=Math.floor(angle/TAU);if(Math.floor(previousAngle/Math.PI)!==Math.floor(angle/Math.PI))beep(220+rnd(0,120),.045,'triangle',.018,-130)}
for(const e of enemies){e.flash=Math.max(0,e.flash-dt);let vx=player.x-e.x,vy=player.y-e.y,d=Math.hypot(vx,vy)||1;let speed=e.speed;
if(e.type==='boss'){e.action-=dt;if(e.mode==='windup'){speed=0;e.charge-=dt;if(e.charge<=0){e.mode='charge';e.charge=.58;const l=Math.hypot(e.targetX-e.x,e.targetY-e.y)||1;e.chargeX=(e.targetX-e.x)/l;e.chargeY=(e.targetY-e.y)/l;beep(100,.2,'sawtooth',.04)}}else if(e.mode==='charge'){vx=e.chargeX;vy=e.chargeY;d=1;speed=330;e.charge-=dt;if(e.charge<=0){e.mode='hunt';e.action=1.9}}else if(e.action<=0){e.phase++;if(e.phase%2===0){e.mode='windup';e.charge=.95;e.targetX=player.x;e.targetY=player.y;speed=0}else{const n=e.hp<e.maxHp*.5?14:10;for(let i=0;i<n;i++){const a=i*TAU/n+e.phase*.37;projectiles.push({x:e.x,y:e.y-22,vx:Math.cos(a)*105,vy:Math.sin(a)*105,life:6})}burst(e.x,e.y-22,'#d57c9e',15);e.action=2.7;beep(180,.2,'sine',.045,100)}}}
e.x=clamp(e.x+vx/d*speed*dt+e.knockX*dt,30,W-30);e.y=clamp(e.y+vy/d*speed*dt+e.knockY*dt,50,H-20);e.knockX*=Math.exp(-9*dt);e.knockY*=Math.exp(-9*dt);
// Each blade pass may hit an enemy once; angular sweep keeps fast attacks reliable.
if(player.armed&&dist(player,e)<player.reach+e.r){let bearing=Math.atan2(e.y-player.y,e.x-player.x);let phase=(angle-bearing+TAU*1000)%TAU;const sweep=dt*TAU*player.attackRate+.95;let hitPass=Math.floor((angle-bearing)/TAU);if(phase<sweep&&e.lastHit!==hitPass){e.lastHit=hitPass;e.hp-=player.damage;e.flash=.16;e.knockX=-vx/d*(e.type==='boss'?10:90);e.knockY=-vy/d*(e.type==='boss'?10:90);burst(e.x,e.y-12,e.type==='shade'?'#92d5c2':'#d678a0',6);floating(Math.round(player.damage),e.x,e.y-30);beep(390,.045,'square',.009,-220)}}
if(e.hp>0&&Math.hypot(e.x-player.x,e.y-player.y)<e.r+10)damagePlayer();if(state!=='playing')break;
}
if(state!=='playing')return;
for(let i=enemies.length-1;i>=0;i--)if(enemies[i].hp<=0){const e=enemies[i];burst(e.x,e.y-12,e.type==='boss'?'#efc584':e.type==='shade'?'#6fbaa9':'#ae638d',e.type==='boss'?85:20);if(e.type==='boss')shake=10;killCount++;if(Math.random()<.10&&e.type!=='boss')drops.push({x:e.x,y:e.y,life:14});enemies.splice(i,1)}
// Soft separation preserves readable silhouettes in a horde.
for(let i=0;i<enemies.length;i++)for(let j=i+1;j<enemies.length;j++){const a=enemies[i],b=enemies[j],d=dist(a,b),min=(a.r+b.r)*.68;if(d>0&&d<min){const push=(min-d)*dt*2,xx=(a.x-b.x)/d*push,yy=(a.y-b.y)/d*push;a.x+=xx;a.y+=yy;b.x-=xx;b.y-=yy}}
for(let i=projectiles.length-1;i>=0;i--){let p=projectiles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(dist(p,player)<13){damagePlayer();p.life=0}if(p.life<=0||p.x<0||p.x>W||p.y<0||p.y>H)projectiles.splice(i,1)}
for(let i=drops.length-1;i>=0;i--){const p=drops[i];p.life-=dt;if(dist(p,player)<24&&player.hp<player.maxHp){player.hp++;floating('+1 ♥',player.x,player.y-40,'#ef8da1');beep(740,.15,'triangle',.04);drops.splice(i,1)}else if(p.life<=0)drops.splice(i,1)}
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1)}for(let i=texts.length-1;i>=0;i--){texts[i].y-=25*dt;texts[i].life-=dt;if(texts[i].life<=0)texts.splice(i,1)}for(let i=afterimages.length-1;i>=0;i--){afterimages[i].life-=dt;if(afterimages[i].life<=0)afterimages.splice(i,1)}
if(state==='playing'&&((wave<5&&spawned>=configs[wave].count&&enemies.length===0)||(wave===5&&enemies.length===0)))completeWave();updateHud()}
function render(){ctx.save();if(shake&&state==='playing')ctx.translate(rnd(-shake,shake),rnd(-shake,shake));ctx.drawImage(ground,0,0);const menuMode=state==='menu'||(state==='help'&&previousState==='menu');let px=menuMode?654:player.x,py=menuMode?310:player.y;glow(500,285,200,'#7bac5b0b');
for(const p of [[180,170],[780,170],[184,412],[779,412]]){glow(p[0],p[1]-12,49,'#edab5c22');rect(ctx,p[0]-3,p[1]-4,6,12,'#49514d');rect(ctx,p[0]-4,p[1]-11,8,5,'#a67c4d');rect(ctx,p[0]-2,p[1]-19+Math.sin(time*9)*2,4,9,'#e8b86d');rect(ctx,p[0],p[1]-16,2,5,'#fff3be')}
if(sword||menuMode){const s=menuMode?{x:707,y:277}:sword;const bob=Math.sin(time*3)*3;glow(s.x,s.y-10,60,'#eac47b30');ctx.strokeStyle='#e5ca8666';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(s.x,s.y+4,20+Math.sin(time*3)*2,9,0,0,TAU);ctx.stroke();rect(ctx,s.x-13,s.y-1,26,8,'#65716a');rect(ctx,s.x-9,s.y-5,18,6,'#98a294');blade(s.x,s.y-17+bob,.2,1.2);for(let i=0;i<5;i++){const a=time*.5+i*1.25;rect(ctx,s.x+Math.cos(a)*23,s.y-15+Math.sin(a*1.7)*21,2,2,'#eddb9b')}if(!menuMode){ctx.textAlign='center';ctx.font='bold 10px monospace';ctx.fillStyle='#f2d39c';ctx.fillText('COLETE A ESPADA',s.x,s.y-66);ctx.fillText('↓',s.x,s.y-50)}}
for(const d of drops){glow(d.x,d.y,18,'#ec69852b');ctx.fillStyle='#ef8492';ctx.font='bold 18px monospace';ctx.textAlign='center';ctx.fillText('♥',d.x,d.y+Math.sin(time*4)*3)}
let entities=[...scenery.map(s=>({...s,scenery:true})),...enemies,{type:'hero',x:px,y:py,isPlayer:true}];if(menuMode){entities=entities.filter(e=>e.scenery||e.isPlayer);for(const p of [[816,241,'vamp'],[767,381,'shade'],[583,402,'vamp'],[876,330,'bat'],[549,191,'bat']])entities.push({x:p[0],y:p[1],type:p[2],phase:p[0]})}
for(const e of enemies)if(e.type==='boss'&&e.mode==='windup'){ctx.strokeStyle='#f66b8166';ctx.lineWidth=28;ctx.setLineDash([7,9]);ctx.beginPath();ctx.moveTo(e.x,e.y);const len=Math.hypot(e.targetX-e.x,e.targetY-e.y)||1;ctx.lineTo(e.x+(e.targetX-e.x)/len*220,e.y+(e.targetY-e.y)/len*220);ctx.stroke();ctx.setLineDash([]);glow(e.x,e.y,75,'#d7456944')}
for(const a of afterimages){ctx.globalAlpha=a.life*.9;drawSprite('hero',a.x,a.y,2,0,player.flip)}ctx.globalAlpha=1;
entities.sort((a,b)=>a.y-b.y).forEach(e=>{if(e.scenery){if(e.type==='tree')tree(e.x,e.y,e.s);else pillar(e.x,e.y);return}shadow(e.x,e.y,e.type==='boss'?29:13);let frame=e.isPlayer?((player.moving||menuMode)&&Math.sin(time*12)>0?1:0):(Math.sin(time*(e.type==='bat'?13:8)+(e.phase||0))>0?1:0);if(e.isPlayer){glow(e.x,e.y-12,40,'#e6c08212');if(player.invuln>0&&!menuMode&&Math.floor(time*14)%2===0)ctx.globalAlpha=.4;drawSprite('hero',e.x,e.y,2,frame,player.flip);ctx.globalAlpha=1}else{if(e.flash>0)ctx.globalAlpha=.5;drawSprite(e.type,e.x,e.y+(e.type==='bat'?Math.sin(time*6+e.x)*4:0),e.type==='boss'?3.7:2,frame,e.x>px);ctx.globalAlpha=1}});
if(player.armed&&!menuMode){const cy=player.y-11,r=player.reach-10;ctx.save();ctx.translate(player.x,cy);for(let i=10;i>=0;i--){const a=angle-i*.1;ctx.strokeStyle=`rgba(221,239,201,${(1-i/11)*.25})`;ctx.lineWidth=3+(1-i/11)*5;ctx.beginPath();ctx.arc(0,0,r,a-.12,a+.09);ctx.stroke()}ctx.strokeStyle='#fff2c7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,r+8,angle-.55,angle);ctx.stroke();ctx.restore();blade(player.x+Math.cos(angle)*(r-11),cy+Math.sin(angle)*(r-11),angle+Math.PI/2,1);glow(player.x+Math.cos(angle)*r,cy+Math.sin(angle)*r,17,'#ffedb331')}
for(const p of projectiles){glow(p.x,p.y,17,'#f76e8b3a');rect(ctx,p.x-4,p.y-4,8,8,'#ad426f');rect(ctx,p.x-2,p.y-2,4,4,'#ffd1cd')}
for(const p of particles){ctx.globalAlpha=clamp(p.life/.3,0,1);rect(ctx,p.x,p.y,p.size,p.size,p.color)}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font='bold 12px monospace';for(const t of texts){ctx.globalAlpha=Math.min(1,t.life*3);ctx.fillStyle='#151a27';ctx.fillText(t.text,t.x+1,t.y+1);ctx.fillStyle=t.color;ctx.fillText(t.text,t.x,t.y)}ctx.globalAlpha=1;
// Quiet floating spores and drifting moonlight stay on the pixel grid.
for(let i=0;i<(globalThis.RubraPreferences?.particles===false?0:25);i++){const x=(i*139+Math.sin(time*.4+i)*19+W)%W,y=(i*73-time*(2+i%3)+H*100)%H;ctx.globalAlpha=.2+Math.sin(time*2+i)*.17;rect(ctx,x,y,2,2,i%3?'#c3dfb2':'#edca87')}ctx.globalAlpha=1;let vignette=ctx.createRadialGradient(W/2,H/2,170,W/2,H/2,570);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#071021b0');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);ctx.restore()}
function loop(now){const dt=Math.min((now-last)/1000||0,.04);last=now;update(dt);render();requestAnimationFrame(loop)}
$('startButton').onclick=start;$('retryButton').onclick=start;$('pauseButton').onclick=togglePause;$('resumeButton').onclick=togglePause;$('quitButton').onclick=showMenu;$('endMenuButton').onclick=showMenu;
$('soundButton').onclick=()=>{soundOn=!soundOn;$('soundButton').textContent=soundOn?'♫ Som: on':'♫ Som: off';$('soundButton').setAttribute('aria-label',soundOn?'Desativar som':'Ativar som');initAudio();beep(523,.14,'triangle',.04)};
$('helpTop').onclick=()=>{if(state==='help')return;previousState=state;state='help';keys.clear();$('help').classList.remove('hidden')};$('closeHelp').onclick=()=>{state=previousState;$('help').classList.add('hidden')};
document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(state!=='upgrade')return;const u=b.dataset.upgrade;if(u==='damage')player.damage*=1.35;if(u==='speed')player.attackRate*=1.25;if(u==='reach'){player.maxHp++;player.hp++;player.reach*=1.15}nextWave()});
window.addEventListener('keydown',e=>{if(state!=='playing'&&e.target?.type==='range')return;const k=e.key.toLowerCase();if((k===' '&&state==='playing')||['arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if((k==='p'||k==='escape')&&!e.repeat){if(state==='help'){$('closeHelp').click()}else togglePause()}keys.add(k);if((k===' '||k==='shift')&&!e.repeat)dash()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')togglePause()});
let activePointer=null;function moveStick(e){const r=$('joystick').getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/32,y=(e.clientY-r.top-r.height/2)/32;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}joystick={x,y};$('stick').style.transform=`translate(${x*26}px,${y*26}px)`} $('joystick').addEventListener('pointerdown',e=>{activePointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);moveStick(e)});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===activePointer)moveStick(e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(ev,()=>{activePointer=null;joystick={x:0,y:0};$('stick').style.transform=''});$('dashTouch').addEventListener('pointerdown',e=>{e.preventDefault();dash()});
// Keep the entire arena visible on portrait screens; fit a narrower logical viewport by letterboxing.
function fit(){if(matchMedia('(max-width:520px) and (orientation:portrait)').matches){canvas.style.objectFit='contain';$('arena').style.background='#101c27'}else canvas.style.objectFit='fill'}window.addEventListener('resize',fit);fit();reset();requestAnimationFrame(loop);
