'use strict';
// Source portraits stay intact. Canvas removes the opaque checkerboard at import.
const RubraProfane=(()=>{
 const enemyFrames={},weaponImages={};
 function crop(image,rect,threshold=160){return RubraSprites.extract(image,rect,threshold);}
 function clearHoles(c,threshold=145){const q=c.getContext('2d'),im=q.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4)if(Math.min(d[i],d[i+1],d[i+2])>threshold&&Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])<32)d[i+3]=0;q.putImageData(im,0,0);return c;}
 function cut(image,rect,threshold=160){const raw=crop(image,rect,threshold),c=document.createElement('canvas');c.width=raw.width;c.height=raw.height;c.getContext('2d').drawImage(raw.canvas,raw.left,raw.top,raw.width,raw.height,0,0,c.width,c.height);return c;}
 function prepare(images){const heroes={};for(const id of RubraConfig.profane.heroes){const im=images[id+'Portrait'],raw=crop(im,[0,0,im.width,im.height]),base=RubraSprites.normalize({...raw,canvas:clearHoles(raw.canvas)}),hero={};for(const dir of ['front','back','left','right'])hero[dir]=[base];heroes[id]=hero;}
  for(const [id,end]of [['execution',.82],['bloodwhip',.83],['rosary',.88]]){const im=images[id+'Art'];weaponImages[id]=clearHoles(cut(im,[0,0,im.width,Math.floor(im.height*end)]));}
  const whip=images.bloodwhipClean,matte=document.createElement('canvas');matte.width=whip.width;matte.height=whip.height;const mq=matte.getContext('2d'),pixels=(()=>{mq.drawImage(whip,0,0);return mq.getImageData(0,0,matte.width,matte.height);})();for(let i=0;i<pixels.data.length;i+=4){const d=pixels.data;if(d[i+1]>60&&d[i+1]>d[i]*1.25&&d[i+1]>d[i+2]*1.25)d[i+3]=0;}mq.putImageData(pixels,0,0);weaponImages.bloodwhip=cut(matte,[0,0,matte.width,matte.height],255);
  const rosary=images.rosaryArt;weaponImages.rosaryBlade=clearHoles(cut(rosary,[rosary.width*.515,rosary.height*.448,rosary.width*.45,rosary.height*.421]));
  const relics=images.profaneRelics;for(const [id,x,w]of [['censer',0,421],['knell',438,350],['nails',798,380],['heresy',1170,391],['verdict',1558,490]])weaponImages[id]=clearHoles(cut(relics,[x*relics.width/2048,0,w*relics.width/2048,relics.height]),170);
  const cells={inquisitor:['profaneMonsters1',[[20,48,192,280],[220,55,155,275]],848,1264],fanatic:['profaneMonsters1',[[185,540,65,112],[272,540,75,112],[365,540,70,112],[184,660,70,105]],848,1264],ethereal:['profaneMonsters1',[[30,820,118,164],[163,828,125,155],[299,836,118,147],[443,826,120,150]],848,1264],profaneGargoyle:['profaneMonsters2',[[30,65,170,176],[220,65,173,176],[410,65,167,176],[585,57,148,184]],1408,768],fallenKnight:['profaneMonsters2',[[60,305,174,200],[312,305,158,200],[482,305,150,200],[635,305,145,200]],1408,768],flesh:['profaneMonsters2',[[296,565,188,194],[490,545,167,214],[655,545,176,214]],1408,768]};
  for(const [id,[source,rects,w,h]]of Object.entries(cells)){const im=images[source];enemyFrames[id]=rects.map(rect=>{const c=cut(im,rect.map((v,i)=>v*(i%2?im.height/h:im.width/w)),source==='profaneMonsters2'?75:155);return source==='profaneMonsters1'?clearHoles(c,180):c;});images[id]=enemyFrames[id][0];}
  const im=images.profaneExtras;for(const [row,id]of ['templeHound','fallenSeraph'].entries()){enemyFrames[id]=Array.from({length:4},(_,col)=>cut(im,[col*im.width/4,row*im.height/2,im.width/4,im.height/2],75));images[id]=enemyFrames[id][0];}
  return heroes;
 }
 function buildGround(){ground.width=map.world.width;ground.height=map.world.height;g.imageSmoothingEnabled=false;g.drawImage(assetImages.profaneMap,0,0,ground.width,ground.height);scenery.length=0;}
 function valid(p,m,r,ghost=false){if(!ghost)return RubraCore.validPoint(p,m,r);const b=m.bounds;return Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x-r>=b.x&&p.y-r>=b.y&&p.x+r<=b.x+b.w&&p.y+r<=b.y+b.h;}
 function charge(dt=0,hit=false){if(run?.character!=='malthor')return;let energy=Math.max(0,Math.min(.5,Number(run.darkEnergy)||0));if(hit){energy=Math.min(.5,energy+.025);run.lastDarkHit=elapsed;}else if(elapsed-(run.lastDarkHit||0)>4)energy=Math.max(0,energy-dt*.09);run.darkEnergy=energy;player.range=C.characters.malthor.range*(1+energy);}
 function events(){if(map!==C.maps.profane||elapsed<270||run.gargoyleSpawned)return;const cfg=C.enemies.profaneGargoyle,pos=K.spawnPoint(map,player,C.combat.bossSafeDistance,cfg.r);if(!pos)return;if(enemies.length>=C.limits.enemies){const candidates=enemies.filter(e=>e.type!=='boss'&&!e.cfg.miniBoss).sort((a,b)=>dist(b,player)-dist(a,player));if(!candidates.length)return;enemies=enemies.filter(e=>e!==candidates[0]);}enemies.push(newEnemy('profaneGargoyle',pos));run.gargoyleSpawned=true;toast('Gárgula de Pedra Profana · mini-chefe!',4);RubraAudio.event('boss');snapshot();}
 function cleave(slot,w,target){if(!target)return;const a=Math.atan2(target.y-player.y,target.x-player.x);effect({kind:'cleave',weapon:slot.id,x:player.x,y:player.y-8,angle:a,arc:w.arc,r:w.range,color:w.color,life:.48,max:.48});for(const e of alive()){const angle=Math.atan2(e.y-player.y,e.x-player.x),delta=Math.atan2(Math.sin(angle-a),Math.cos(angle-a));if(dist(e,player)>w.range+e.r||Math.abs(delta)>w.arc/2)continue;damageEnemy(e,w.damage,w);if(!e.dead&&e.type!=='boss'&&!e.cfg.miniBoss)moveBody(e,Math.cos(angle)*28,Math.sin(angle)*28);if(state!=='playing')break;}}
 function bossAttack(e){if(map!==C.maps.profane||e.type!=='boss')return false;e.phase++;e.telegraph={kind:'ring',summon:e.phase%3===0,x:e.x,y:e.y,time:1.2,count:e.hp<e.maxHp*.5?12:8};e.action=e.cfg.interval*(e.hp<e.maxHp*.5?.85:1);return true;}
 function bossRelease(e,t){if(map!==C.maps.profane||e.type!=='boss')return false;if(t.summon){for(const key of ['fanatic','fanatic','templeHound','fanatic'])spawnMob(key);}else for(let i=0;i<t.count&&shots.length<C.limits.projectiles;i++){const a=i*TAU/t.count+e.phase*.31;shots.push({id:++entityId,x:e.x,y:e.y-8,vx:Math.cos(a)*76,vy:Math.sin(a)*76,life:7,damage:e.cfg.damage,color:'#afff96',hostile:true,hit:new Set(),pierce:1});}return true;}
 function paint(q,id){const im=weaponImages[id];if(im){const s=Math.min(30/im.width,30/im.height);q.drawImage(im,-im.width*s/2,-im.height*s/2,im.width*s,im.height*s);return true;}if(!['censer','knell','nails','heresy','verdict'].includes(id))return false;
  q.lineWidth=2;q.strokeStyle='#dbc4a0';q.fillStyle='#33273d';
  if(id==='nails'){q.rotate(.3);q.fillStyle='#261e31';q.fillRect(-4,-13,8,6);q.fillStyle='#bbb8d1';q.fillRect(-2,-10,4,19);q.beginPath();q.moveTo(-2,9);q.lineTo(0,15);q.lineTo(2,9);q.fill();q.fillStyle='#eff0ec';q.fillRect(-1,-9,1,16);q.fillStyle='#9d5073';q.fillRect(-4,-11,8,2);}
  else if(id==='heresy'||id==='verdict'){q.fillRect(-11,-13,22,27);q.strokeRect(-11,-13,22,27);q.fillStyle='#765474';q.fillRect(-8,-11,3,23);q.fillStyle=id==='verdict'?'#b7ee9a':'#bb91cf';q.fillRect(-1,-8,3,18);q.fillRect(-5,-4,11,3);q.fillRect(-8,11,17,2);q.fillStyle='#f4dfb0';for(const x of [-9,7])for(const y of [-11,9])q.fillRect(x,y,3,3);q.fillStyle='#2e1b30';q.fillRect(4,3,4,5);q.fillStyle='#e7c381';q.fillRect(5,4,2,3);q.fillStyle='#54364e';for(let y=-9;y<9;y+=4){q.fillRect(-3,y,1,2);q.fillRect(6,y,2,1);}q.fillStyle='#f8e4b8';q.fillRect(-8,12,15,1);}
  else {q.beginPath();q.moveTo(-10,8);q.lineTo(-7,-7);q.quadraticCurveTo(0,-16,7,-7);q.lineTo(10,8);q.closePath();q.fill();q.stroke();q.fillStyle='#aa8b62';q.fillRect(-12,7,24,3);q.fillStyle='#edcf91';q.fillRect(-1,10,3,4);q.fillStyle='#5c384f';q.fillRect(-3,-6,2,12);if(id==='censer'){q.strokeStyle='#b7c4ad';for(const x of [-8,8]){q.beginPath();q.moveTo(x,3);q.lineTo(0,-15);q.stroke();}q.fillStyle='#a4eb85';q.fillRect(-4,-3,3,6);q.fillRect(1,-6,2,7);}q.fillStyle='#e5c08d';q.fillRect(-7,5,14,1);q.fillStyle='#715d59';q.fillRect(-5,-5,2,9);q.fillStyle='#332333';q.fillRect(4,-4,2,10);for(let j=0;j<3;j++){q.fillStyle=j%2?'#bfae8a':'#6d5356';q.fillRect(-8+j*6,2,3,2);}q.fillStyle='#ead9b3';q.fillRect(-3,-12,6,2);}
  return true;
 }
 function effectArt(q,e,t){if(e.kind!=='cleave'&&e.weapon!=='bloodwhip'&&!(e.kind==='storm'&&['censer','verdict'].includes(e.weapon)))return false;q.save();const age=e.max-e.life,fade=Math.min(1,e.life/.25);q.globalAlpha=fade;q.strokeStyle=e.color;
  if(e.kind==='cleave'){const a=e.angle-e.arc/2+Math.min(1,age/.3)*e.arc;for(let i=0;i<4;i++){q.globalAlpha=fade*(.55-i*.11);q.lineWidth=8-i;q.beginPath();q.arc(e.x,e.y,e.r-i*5,a-.6,a);q.stroke();}q.globalAlpha=fade;RubraWeaponArt.item(q,'execution',e.x+Math.cos(a)*e.r*.8,e.y+Math.sin(a)*e.r*.8,a+Math.PI/4,1.9);}
  else if(e.weapon==='bloodwhip'){q.strokeStyle='#2b101b';q.lineWidth=8;q.beginPath();q.moveTo(e.x,e.y);for(let i=1;i<=20;i++){const p=i/20,offset=Math.sin(p*12-age*20)*7*Math.sin(p*Math.PI);q.lineTo(e.x+(e.tx-e.x)*p,e.y+(e.ty-e.y)*p+offset);}q.stroke();q.strokeStyle='#ce4659';q.lineWidth=6;q.stroke();q.strokeStyle='#68311f';q.lineWidth=3;q.stroke();q.strokeStyle='#d28b58';q.setLineDash([2,6]);q.lineWidth=1.5;q.stroke();q.setLineDash([]);RubraWeaponArt.item(q,'bloodwhip',e.x,e.y,0,.8);}
  else{q.globalAlpha=.12*fade;q.fillStyle=e.color;q.beginPath();q.arc(e.x,e.y,e.r,0,TAU);q.fill();for(let j=0;j<3;j++){q.globalAlpha=fade*(.55-j*.12);q.lineWidth=j===0?3:1;q.beginPath();q.arc(e.x,e.y,e.r*(.4+j*.3),age*(j%2?1:-1),age*(j%2?1:-1)+TAU*.9);q.stroke();}for(let i=0;i<12;i++){const a=i*TAU/12+age*.25,r=e.r*.85;q.globalAlpha=.75*fade;q.save();q.translate(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r);q.rotate(a);q.fillStyle=e.color;q.fillRect(-2,-5,4,10);q.fillRect(-5,-1,10,2);q.restore();}q.globalAlpha=fade;RubraWeaponArt.item(q,e.weapon,e.x,e.y-10-Math.sin(age*4)*5,Math.sin(age)*.1,1.6);}
  q.restore();return true;
 }
 function rosaryOrbit(q,p,t,w){q.save();const radius=w.range;for(let i=0;i<48;i++){const a=t*1.25+i*TAU/48,x=p.x+Math.cos(a)*radius,y=p.y+Math.sin(a)*radius;q.fillStyle='#250c19';q.beginPath();q.arc(x,y,2.5,0,TAU);q.fill();q.fillStyle='#a52c46';q.fillRect(Math.round(x)-1,Math.round(y)-1,2,2);q.fillStyle='#f1969f';q.fillRect(Math.round(x)-1,Math.round(y)-1,1,1);}for(let i=0;i<w.count;i++){const a=t*C.visuals.orbitSpeed+i*TAU/w.count;q.globalAlpha=.2;q.strokeStyle='#ef536c';q.lineWidth=3;q.beginPath();q.arc(p.x,p.y,radius,a-.4,a);q.stroke();q.globalAlpha=1;RubraWeaponArt.item(q,'rosaryBlade',p.x+Math.cos(a)*radius,p.y+Math.sin(a)*radius,a+Math.PI/2,1.05);}q.restore();}
 function portrait(q,id,t,on){if(!on)return;q.save();q.fillStyle=id==='malthor'?'#cf6295':id==='vespera'?'#e6a18f':'#e76765';for(let i=0;i<8;i++){const a=t*(id==='vespera'?1.7:.6)+i*TAU/8;q.globalAlpha=.45+.25*Math.sin(t+i);q.fillRect(Math.round(32+Math.cos(a)*24),Math.round(34+Math.sin(a)*22),2,2);}q.restore();}
 return {prepare,buildGround,enemyFrames,weaponImages,valid,charge,events,cleave,bossAttack,bossRelease,paint,effectArt,rosaryOrbit,portrait};
})();
