(function(C){
const weapon=(v)=>({maxLevel:7,count:1,growth:{damage:.27,interval:.045,range:.06},...v});
C.profane={heroes:['karn','malthor','vespera'],inherited:['absolute','comet','prism'],weapons:['execution','bloodwhip','rosary','censer','knell','nails','heresy'],bossWeapon:'verdict'};
Object.assign(C.characters,{
 karn:{name:'Karn, o Carrasco',description:'O destruidor de elites. A armadura pesa; o machado abre espaço.',hp:10,speed:136,radius:10,weapon:'execution',damage:1.6,attackSpeed:.9,range:1,dashCooldown:2.6,unlock:'Derrote Skarn para liberar o Santuário Profano',passive:'Execução · +60% de dano; arco frontal pesado empurra ameaças. Mais vida, menor mobilidade.'},
 malthor:{name:'Malthor, o Herege',description:'Converte impactos em energia sombria para dominar corredores.',hp:8,speed:162,radius:8,weapon:'bloodwhip',price:1500,purchaseMap:'profane',damage:1.42,attackSpeed:1.28,range:1,dashCooldown:2,unlock:'Libere o Santuário Profano e compre por 1500 de ouro',passive:'Herança sombria · acertos acumulam até +50% de alcance; começa a dissipar após 4 s sem atingir.'},
 vespera:{name:'Vespera, a Devota Sombria',description:'Desliza entre colunas protegida por um rosário de lâminas.',hp:7,speed:182,radius:8,weapon:'rosary',price:2000,purchaseMap:'profane',damage:1.18,attackSpeed:1.65,range:1.08,dashCooldown:1.6,unlock:'Libere o Santuário Profano e compre por 2000 de ouro',passive:'Devoção veloz · +65% de cadência, maior mobilidade e esquiva a cada 1,6 s.'}
});
Object.assign(C.weapons,{
 execution:weapon({name:'Machado da Execução',description:'Um arco frontal pesado atinge grupos e empurra inimigos comuns.',kind:'cleave',damage:102,interval:1.95,range:116,arc:2.25,color:'#cf626e',unlock:'Libere o Santuário Profano; arma principal de Karn'}),
 bloodwhip:weapon({name:'Chicote de Sangue',description:'Estalo cortante em linha reta, atravessando todos os alvos no trajeto.',kind:'beam',damage:48,interval:.92,range:210,width:13,color:'#f26476',unlockSeconds:45,unlock:'Sobreviva 45 segundos no Santuário Profano ou compre Malthor'}),
 rosary:weapon({name:'Lâminas do Rosário',description:'Lâminas de um rosário carmesim orbitam continuamente, retalhando ameaças próximas.',kind:'orbital',damage:22,interval:.68,range:74,count:3,color:'#df566e',unlockSeconds:90,unlock:'Sobreviva 90 segundos no Santuário Profano ou compre Vespera'}),
 censer:weapon({name:'Turíbulo das Almas',description:'Um incensário invoca fumaça espectral: dano periódico e lentidão em área.',kind:'storm',damage:24,interval:3.8,range:300,radius:90,duration:3,tick:.65,slow:.6,slowTime:1,color:'#a3db86',unlockSeconds:150,unlock:'Sobreviva 2:30 no Santuário Profano'}),
 knell:weapon({name:'Sino da Ruína',description:'Um sino rachado anuncia uma explosão circular de energia profana.',kind:'area',damage:74,interval:3,range:320,radius:96,color:'#c7b684',unlockSeconds:210,unlock:'Sobreviva 3:30 no Santuário Profano'}),
 nails:weapon({name:'Pregos do Mártir',description:'Duas estacas rúnicas de ferro atravessam até seis inimigos cada.',kind:'piercing',damage:34,interval:1.05,range:350,count:2,speed:370,pierce:6,color:'#c3b4d6',unlockSeconds:300,unlock:'Sobreviva 5:00 no Santuário Profano'}),
 heresy:weapon({name:'Evangelho das Sombras',description:'Um tomo proibido conecta até quatro inimigos com raios de maldição.',kind:'chain',damage:41,interval:1.75,range:290,count:4,jumpRange:150,color:'#bd97de',unlockSeconds:390,unlock:'Sobreviva 6:30 no Santuário Profano'}),
 verdict:weapon({name:'Édito do Inquisidor',description:'Relíquia do chefe: um selo de julgamento desencadeia seis pulsos devastadores e lentidão.',kind:'storm',damage:125,interval:3.6,range:400,radius:120,duration:2.9,tick:.5,slow:.5,slowTime:1.2,color:'#bdeba0',unlock:'Derrote O Inquisidor Esquecido no Santuário Profano'})
});
const mob=(name,hp,speed,xp,asset,extra={})=>({name,hp,speed,xp,damage:1,goldChance:.35,gold:5,r:13,behavior:'chase',asset,size:52,...extra});
Object.assign(C.enemies,{
 fanatic:mob('Monge Fanático',82,32,8,'fanatic'),templeHound:mob('Cão do Templo',58,76,7,'templeHound',{size:40,r:12}),
 ethereal:mob('Aparição Etérea',108,49,11,'ethereal',{ghost:true,size:54}),
 flesh:mob('Abominação de Carne',480,28,25,'flesh',{r:23,size:78,damage:2,gold:12,goldChance:.7}),
 zealot:mob('Monge Enfurecido',125,57,12,'fanatic',{ring:'#ae4971'}),
 fallenSeraph:mob('Seraph Caído',195,35,18,'fallenSeraph',{behavior:'ranged',attackInterval:3.4,size:66,gold:9}),
 fallenKnight:mob('Cavaleiro Caído',290,39,22,'fallenKnight',{r:18,size:64,damage:2,gold:12}),
 profaneGargoyle:mob('Gárgula de Pedra Profana',3200,37,160,'profaneGargoyle',{r:30,size:103,damage:2,gold:65,goldChance:1,miniBoss:true,behavior:'ranged',attackInterval:3.8,ring:'#a5df88'})
});
C.maps.profane={name:'Santuário Profano',subtitle:'CAPÍTULO III',description:'Claustros arruinados, colunas e fogo espectral. Quatro ondas; Inquisidor aos 9 minutos.',duration:600,bossAt:540,finishOnBoss:true,unlock:'Derrote Skarn no Santuário do Inverno',spawn:{x:1920,y:1910},bounds:{x:200,y:260,w:3440,h:2100},world:{width:3840,height:2560,spawnOuter:470,despawnDistance:1100},maxWeaponLevel:7,spawnInterval:1.4,minInterval:.36,enemies:['fanatic','templeHound'],weapons:[...C.profane.inherited,...C.profane.weapons,'verdict'],startWeapon:'execution',preview:'profaneMap',boss:{name:'O Inquisidor Esquecido',hp:13500,damage:2,speed:25,r:32,size:112,asset:'inquisitor',gold:320,interval:3.6},obstacles:[{x:1920,y:1260,r:70,kind:'altar'},...[[430,310],[520,220],[470,405],[475,650],[435,760],[560,876],[648,905],[1105,308],[1015,220],[1062,405],[1062,650],[1105,770],[900,870]].map(([x,y])=>({x:x*2.5,y:y*2.5,r:36,kind:'pillar'}))],waves:[{at:0,name:'Onda 1 · O limiar',interval:1.4,pool:['fanatic','fanatic','templeHound']},{at:150,name:'Onda 2 · Vozes entre pilares',interval:.95,pool:['fanatic','templeHound','ethereal']},{at:300,name:'Onda 3 · Carne e penitência',interval:.62,pool:['zealot','zealot','flesh','ethereal','templeHound']},{at:450,name:'Onda 4 · A última liturgia',interval:.36,pool:['zealot','zealot','fallenSeraph','flesh','fallenKnight','ethereal']}]};
Object.assign(C.assets,{bloodwhipClean:'assets/profane/bloodwhip-clean.png',profaneRelics:'assets/profane/relics.png',profaneMap:'assets/profane/map.png',profaneExtras:'assets/profane/extra-mobs.png',profaneMonsters1:'assets/profane/monsters-1.jpg',profaneMonsters2:'assets/profane/monsters-2.jpg',karnPortrait:'assets/profane/karn.jpg',malthorPortrait:'assets/profane/malthor.jpg',vesperaPortrait:'assets/profane/vespera.jpg',executionArt:'assets/profane/execution.jpg',bloodwhipArt:'assets/profane/bloodwhip.jpg',rosaryArt:'assets/profane/rosary.jpg'});
if(typeof module!=='undefined')module.exports=C;
})(typeof RubraConfig!=='undefined'?RubraConfig:module.exports);
