'use strict';
const RubraVictory=(()=>{
 const rewards={tutorial:{weapon:'dagger',next:'Noctis e a Necrópole Carmesim estão disponíveis para sua próxima expedição.'},necropolis:{weapon:'lance',next:'Nivor e o Santuário do Inverno estão disponíveis para sua próxima expedição.'},ice:{weapon:'absolute',next:'Karn e o Santuário Profano estão disponíveis para sua próxima expedição.'},profane:{weapon:'verdict',next:'O Santuário Profano foi conquistado. Sua relíquia está disponível no Arsenal.'}};
 function show(win){
  const panel=$('end'),abandoned=save.lastResult?.outcome==='abandon';panel.classList.add('menu-screen','victory-screen');panel.classList.toggle('defeat-screen',!win);document.body.classList.add('in-menus');$('victoryDetails').classList.remove('hidden');$('victoryDestinations').classList.remove('hidden');$('endText').classList.add('sr-only');$('retryButton').textContent=win||abandoned?'Nova expedição':'Tentar novamente';
  {const c=C.characters[run.character],r=rewards[run.map];$('endEyebrow').textContent=(win?'EXPEDIÇÃO CONCLUÍDA':abandoned?'EXPEDIÇÃO ENCERRADA':'O ÚLTIMO FÔLEGO')+' · '+map.subtitle;$('endTitle').textContent=win?'A noite é sua':abandoned?'Até a próxima caçada':'A noite continua';$('victoryBoss').textContent=win?map.boss.name+' foi derrotado':abandoned?'Você deixou a arena. Seu ouro está a salvo.':'Seu caçador caiu. Sua jornada ainda não terminou.';$('resultHunterLabel').textContent=win?'CAÇADOR VITORIOSO':'SEU CAÇADOR';$('resultCaption').textContent=win?'O guardião caiu':'Registro da expedição';$('victoryHunter').textContent=c.name;$('victoryMap').textContent=map.name;$('victoryTime').textContent=formatTime(elapsed);$('victoryKills').textContent=String(killCount);$('victoryGold').textContent=String(run.gold);$('victoryBalance').textContent='Saldo total: '+save.gold+' de ouro';$('resultRelic').classList.toggle('hidden',!win);$('resultArsenal').classList.toggle('hidden',win);
   if(win){$('victoryReward').innerHTML=RubraWeaponArt.iconHtml(r.weapon);$('victoryWeapon').textContent=C.weapons[r.weapon].name;$('victoryWeaponText').textContent=C.weapons[r.weapon].description;$('victoryNext').textContent=r.next;}else{$('resultWeaponList').innerHTML=run.weapons.map(w=>`<div title="${C.weapons[w.id].name}">${RubraWeaponArt.iconHtml(w.id)}<span>${C.weapons[w.id].name}</span><small>NV ${w.level}</small></div>`).join('');$('victoryNext').textContent='O ouro coletado foi guardado. Prepare seu arsenal e volte para enfrentar a noite.';}
   const canvas=$('victoryPortrait'),q=canvas.getContext('2d');q.clearRect(0,0,192,192);q.imageSmoothingEnabled=false;const base=characterFrames[run.character]?.front?.[0];if(base)q.drawImage(base,0,0,192,192);panel.classList.toggle('victory-animated',save.options.particles);
  }
  setTimeout(()=>{if(state==='victory'||state==='gameover')$('retryButton').focus({preventScroll:true});},0);
 }
 return {show};
})();
